### ISSUE TITLE
Larger file uploads end in "Connection reset by peer"

### ISSUE THREAD

**Issue by QuadPiece** [Backblaze/B2_Command_Line_Tool#13]
I am unsure if this is intentional or not, but larger files end with a "Connection reset by peer" after a while. I've been trying to back up a lot of content. But I haven't found a way to recursively upload files, therefore my only option has been to upload a .tar archive of all the files.

Trying to upload smaller files work fine:

![upload1](https://chitoge.quad.moe/storage/sharex/2015-12-17_18-15-23.png)

However, larger file uploads always fail over a 1 gbit/s line:

![upload2](https://chitoge.quad.moe/storage/sharex/2015-12-17_18-31-25.png)

**Comment by bwbeach** [comment]
We have tested uploading files up to the maximum size of 5GB, and they work.

There have been some networking issues is the Bay Area this week because of cut fiber lines, and that affected some Backblaze customers, including me.

For backup, there are some options now.  Backblaze publishes b2_python_pusher as sample code.  It does recursive uploading.  You can find it on the Backblaze web site: https://www.backblaze.com/b2/docs/b2-python-pusher.html

There are also integrations with HashBackup and Duplicity: https://www.backblaze.com/b2/docs/integrations.html

Meanwhile, we'll double check that there aren't any problems with large files on the B2 service.

**Comment by QuadPiece** [comment]
Thank you, may I ask where the 5GB upload limit is mentioned? I can't remember coming across that anywhere. The total size of the .tar I tried uploading was 21 GB

**Comment by bwbeach** [comment]
The size limit is at the top of this page: https://www.backblaze.com/b2/docs/files.html

We should probably make it clearer.  Sorry about that.

**Comment by QuadPiece** [comment]
Ah, that sounds more like a tagline than information, but thanks for clarifying.
