### ISSUE TITLE
Using a lot of threads with sync cause sqlite errors

### ISSUE THREAD

**Issue by nilayp** [Backblaze/B2_Command_Line_Tool#171]
I'm attempting to use the sync command to upload 1 million files using 200 threads. In the log, I'm seeing database errors that prevents an individual file from being uploaded:

`b2_upload(/Volumes/Library/Data/1m-files/file100352.txt, file100352.txt, 1463692063000): OperationalError('database is locked',) database is locked`

When that thread fails - the file is left out of the sync. It never is re-tried.

In addition, infrequently B2 CLI crashes out completely because auth credentials couldn't be retrieved:

`ERROR: Missing account data: database is locked  Use: b2 authorize_account`

**Comment by ppolewicz** [comment]
Hi Nilay,

do you have a full stacktrace by any chance?

**Comment by nilayp** [comment]
Attached is a partial trace. I started sync'ing a folder to B2 with a few million files. Once the compare phase was complete, you'll see "database is locked" errors everywhere.

I ran this with 200 threads.

[database locked trace.txt](https://github.com/Backblaze/B2_Command_Line_Tool/files/319789/database.locked.trace.txt)

**Comment by ppolewicz** [comment]
From sqlite documentation:
> When a database is accessed by multiple connections, and one of the processes modifies the database, the SQLite database is locked until that transaction is committed. The timeout parameter specifies how long the connection should wait for the lock to go away until raising an exception. The default for the timeout parameter is 5.0 (five seconds).

It would seem that your storage device has been unresponsive (likely because it had a long queue of operations done by 200 threads). I would suggest that you symlink `~/.b2_account_info` onto a filesystem which is kept on a different device than the one which is being synced or decrease the amount of threads.

As for the error itself, I have located it and began working on a workaround, but it is not clear for me what should happen when such situation occurs.

What is the behavior you'd expect when the hdd which stores `~/.b2_account_info` is severely overloaded?

**Comment by svonohr** [comment]
Imho, we shouldn't access the SQLite DB that often. Recently I've run a test which revealed that only about 12 upload URLs per seconds can be read from the SQLite DB on a hard disk (on a SSD it's much faster, but not everybody has one). And that result even without putting links back into the DB or reading any files for syncing.

**Comment by ppolewicz** [comment]
We could add caching to slightly decrease load on the database and we could change the design of getting upload urls so that a pool is used for sync and then tokens are put back in the database once, after the uploading is finished.
That becomes complicated though and it doesn't really solve the problem reliably, doesn't maximize the performance.

Some time ago we have considered and dropped a design, where a daemon is spawned on the client machine. This daemon process then accepts connections on localhost tcp port and actually performs operations like uploading, downloading, encrypting etc. Such design resolves the problem of sharing state between multiple processes, that we now support - a client process needs to access the database only once, to determine if the daemon is currently running and on which port. The rest of the operations would be handled by the daemon, which could keep almost everything in memory and only flush things to down to the database when it is shutting down.
The daemon design didn't make much sense when we discussed it before, but now that we are looking into encryption and possibly compression, I thought about a few more issue that the daemon could resolve:
* (performance of database access, as mentioned above)
* depending on compressability and the source device speed, we can hit the CPU bottleneck with hashing, compression and encryption. Once the daemon is up, moving file uploading into a separate *process* would be relatively easy and it would allow usage of more than one CPU on the client machine
* if the user has considerable amount of data to upload and download, flow control can significantly reduce the total time required for the entire job to finish. For example, if we have 100 files to upload and 100 to download, with 2*N threads, then we want N threads to saturate the upload link and the other N threads to saturate the download link
* if we have centralized daemon configuration, we can limit the throughput of upload, download and local io
* if the user has a HDD device, we could trade a bit of memory to optimize for speed. HDDs are quite fast in sequential access and quite slow in random access. By reading/writing from a buffer, we can (maybe) turn the multi-process race to the hard drive into an orderly queue, decreasing utilization of the device and increasing performance (if the device was a bottleneck). (this is not the first thing I would implement)

@bwbeach, @nilayp, @svonohr: do you have any thoughts on how we should proceed?

**Comment by svonohr** [comment]
I don't know how you can implement such a daemon with python. It certainly shouldn't require root privileges or other complicated setup routines. Preferably it should keep looking like a single standalone CLI. Personally I don't plan on using the B2 CLI with multiple parallel processes.

As for the current bug report, I like the simple idea of just not storing the upload URLs in the SQLite DB and only cache them in memory until the process terminates, which was proposed by @bwbeach. This will certainly increase the number of `b2_get_upload_url` requests and slow down consecutive uploads, but this will only be noticable for small files.

**Comment by bwbeach** [comment]
I agree.  The simplest plan is to not store the upload URLs in sqlite.  I'll go ahead and make that change, unless somebody else is eager to.

And thanks to @ppolewicz for the thorough analysis of using a daemon.  We should keep that in mind as we do encryption.

**Comment by ppolewicz** [comment]
@svonohr: the user-side CLI daemon can be implemented in python. It would live as long as any CLI client for this particular user is alive and it would die soon after the last CLI client dies.

I agree that not storing upload URLs in sqlite after every finished upload is a good improvement. It can be further refined by storing the tokens in memory and by saving them to database only in `AccountInfo.__del__`. This would address the slowdown of consecutive uploads of small files mentioned by @svonohr.

Please note that @nilayp reported two issues here: the latter one (`ERROR: Missing account data: database is locked Use: b2 authorize_account`) may still be encountered after the fix, if a drive hosting the database is overloaded and a new process is spawned (parallel to the running sync with 200 threads). The probability of hitting that after the fix is greatly reduced and the error message is fairly ok, so I think we should close the whole #171 (both reported issues) with the fix prepared by @bwbeach.

**Comment by geekpete** [comment]
I see this error with 30 threads.

Agree that store in memory then flush periodically is a better way.

**Comment by geekpete** [comment]
is there any current performance/throughput hit having to update the sqlite db every time?
Any easy way to disable that and compare?

**Comment by ppolewicz** [comment]
@geekpete: in a test done by @svonohr hdd-hosted sqlite database was a bottleneck at 12 upload urls per second, and this was only reading the tokens. It was decided that the urls will not be saved after usage. Whether they will be flushed to disk after sync is finished is not decided (it's tricky - we'd have to guarantee that the `AccountInfo` object will not die before the last transfer ends on the *server* side).

Optimizing the time of single file upload would promote 'single pending' usage pattern, which probably isn't what we are aiming for.
