### ISSUE TITLE
Addition of a "dry run" mode to "b2 sync"

### ISSUE THREAD

**Issue by magnetikonline** [Backblaze/B2_Command_Line_Tool#188]
Firstly, would like to say, love this utility and the B2 service in general.

Having a workable command line client was pretty important to me, and this delivers in spades - so thanks!

One enhancement I would love to see - the option of a "Dry run" mode to `b2 sync` - see what would be copied/deleted without actually doing it to ensure I have crafted a new sync command correctly.

Thanks

   Peter

**Comment by ppolewicz** [comment]
Sounds cool! Would you like to try to implement it? We have unit tests run on a variety of platforms as well as automated style checks so that it is easier to contribute. We also provide code review.

**Comment by magnetikonline** [comment]
@ppolewicz thanks for the reply!

Let me clone and have a dig around - see what I can (possibly) contribute. Otherwise I'm guessing someone else might take up the challenge 😄

**Comment by ppolewicz** [comment]
Due to #197, some changes are planned to be done on the end of this week to the same area of code (`b2/sync.py`) that you might be working on.

**Comment by magnetikonline** [comment]
@ppolewicz thanks for the heads up. Still scraping together time (got a few other pet projects working on!) to get my head into the code. But if we don't mind leaving this around as a placeholder for now that would be great!

Had a review of #197 all makes sense to it's relationship :+1:

**Comment by zackse** [comment]
I have a working proof-of-concept in https://github.com/zackse/B2_Command_Line_Tool/commit/578bb06bcc0e13eb30bcd179d16ba1f6760b07b8.

Couple of questions:

1. The `pre-commit.sh` script reformatted several lines that were otherwise unmodified. Is this desirable or should I split those changes into separate commits?
2. Suggestions/contributions are welcome for testing. Confirming that "nothing happened" is easy enough, though perhaps not the best test.

**Comment by ppolewicz** [comment]
Hi @zackse, thanks for your contribution!

Please make sure that you have a fresh version of `yapf`. Older one could format code differently. It is better to put yapf-induced changed which are not related to your change in a separate commit.

The change that you did could actually work, but it would be much better if the code was restructured so that there is only one `if not dry_run:`. Currently `do_action` does the actual work and reports progress - this should now be decoupled and not calling half of it should be contained in *AbstractAction* or something.
Do you understand what I am trying to say?

**Comment by zackse** [comment]
Makes sense. The approach taken was to avoid restructuring all of the action methods which, as you noted, currently do two things. I'll post an update for review.

**Comment by zackse** [comment]
Updated approach in https://github.com/zackse/B2_Command_Line_Tool/commit/de6a3daf800f05dd3b442d84528ac6bae73a441e. Is this more of what you were looking for?

I omitted the formatting changes, which are still created by the `pre-commit.sh` script. FWIW, I have `yapf 0.13.2` installed.

**Comment by magnetikonline** [comment]
Love your work here @zackse - would love to see this feature land!

**Comment by ppolewicz** [comment]
Contrary to popular belief, restructuring the code so that reflects the new reality is a good thing. Simple putting the difference on top what was there until now using `if` statements, quickly leads to code littered with such pattern, poor testability etc.

I very much like your new change. In fact it is so good, that we would be happy to see more changes done by you in this project. If you need inspiration, there is are 'up-for-grabs' and 'help wanted' labels in github issues, which make it easy to identify pieces of unassigned work, small and big (respectively).

The only thing I'd alter, is to provide a default value for `sync_folders`. If an additional mandatory argument to a "public" function is added, we need to increment the middle version number and it may break stuff for some users.

Regarding yapf, I will run it on the entire source tree and commit to master, then you merge or rebase and create a PR, ok?

Oh, and a test is missing. Would you please change tests to check that when *dry_run* mode is on, reports are accurate but the sync does not actually transfer/delete and so on?

**Comment by ppolewicz** [comment]
ok you can rebase onto master now to get rid of the yapf changes from your branch

**Comment by zackse** [comment]
Thanks for the feedback and catching the missing default value. I updated the branch with that fix and a new test method in `test/test_console_tool.py`. I still need to update `test_b2_command_line.py`, though.

**Comment by ppolewicz** [comment]
Could you please create a PR, so it is easier to review?

**Comment by zackse** [comment]
https://github.com/Backblaze/B2_Command_Line_Tool/pull/269

**Comment by magnetikonline** [comment]
I'll close this, as @zackse has done some excellent work to implement this!
