### ISSUE TITLE
Flawed sync --keepDays semantics

### ISSUE THREAD

**Issue by nicolas17** [Backblaze/B2_Command_Line_Tool#197]
Currently `b2 sync --keepDays 30` deletes file versions older than 30 days, by looking at the modification time of the file. This is fatally flawed. If I have a file that was last modified a year ago, and I accidentally delete it, and sync, the sync will delete the file (because version.modtime = 1 year, > 30 days), leaving only a "hidden" marker. Even though I asked to keep 30 days of history, I can't undo a mistake I did a minute ago and my data is gone.

I think it should use the upload timestamp instead.

**Comment by ppolewicz** [comment]
I think what you might be looking for, is to have 30 days after a mistake (like accidental deletion) to recover the lost data, so the file should be hidden with the first sync after it is deleted. Then it should be truly removed when running the first sync after the file is hidden for more than 30 days.

What you described is a bit different. Could you clear up what you are aiming for?

**Comment by nicolas17** [comment]
What you said is correct, and I don't see how what I described is different. It's also not specific to deletions. If I modify a year-old file and sync with --keepDays 30, to me the only thing that makes sense is to let me go back to the old version until 30 days from now have passed. Current b2 will immediately delete the old version because it's a year old.

**Comment by ppolewicz** [comment]
I now understand the requirement. `make_file_sync_actions` needs to be modified to accommodate this and since it is a long function, it should be refactored on the way.

@bwbeach, @nilayp, do you agree that the behavior should be as described (only after 30 days pass since a file is hidden, it can be really deleted)?

**Comment by bwbeach** [comment]
I like the proposal.  More safety for the user is better.  Leaving the hide marker there for 30 days is safer, and it's also easy to explain what it does.

**Comment by nicolas17** [comment]
Wouldn't it be enough to decide what versions can be deleted based on their upload timestamp instead of the modtime metadata, while keeping the same logic? (I haven't looked at the code closely and I may be very wrong)

**Comment by svonohr** [comment]
I also think that the `--keepDays N` option should keep a history, so that any state of the past N days can be restored. Simply replacing the modtime with the upload time doesn't solve every problem though. Suppose you actually uploaded a file 1 year ago, delete it locally and then do a sync. Then this suffers from the same problem you described. Instead we should keep at least the newest version when hiding a file and subsequent syncs should not delete older versions when there is still a new enough hidden file.

**Comment by ppolewicz** [comment]
In other words, we delete the file once the hide marker becomes older than N days.

**Comment by svonohr** [comment]
Exactly. I still have to think about handling the modtime/upload time issue. It's probably safest to use the newest date when deciding to delete files.

**Comment by ppolewicz** [comment]
Does anyone want to take a shot at implementing this? I can't stand the current `make_file_sync_actions()` and if I am going to implement #197, I'll end up rewriting the whole thing... But on the other hand, having some users accidentally delete their files using current design of `keepDays` is very bad.

I think in this case we only care about creation time of the hide marker. Hide marker shouldn't have a meaningful modification date, so it is clear that creation time is the right thing to look at after all.

**Comment by svonohr** [comment]
I might find time later this week to work on this. Also, I was the last person to touch this function.
