### ISSUE TITLE
Estimated time remaining (for sync command)

### ISSUE THREAD

**Issue by clintinthecode** [Backblaze/B2_Command_Line_Tool#200]
It would be great to have an estimated time remaining.

For example:

tail b2.log s   0.99 / 1.08 TB   7.48 MB/s   3 hours 11 minutes remaining

**Comment by ppolewicz** [comment]
I am almost sure we already do have a time remaining estimate available, unless `--noProgress` is used. Doesn't it work for you?

**Comment by svonohr** [comment]
The sync command does not display the remaining time.

**Comment by ppolewicz** [comment]
ok, so it is only about the `sync` command

**Comment by bwbeach** [comment]
I wasn't sure how to do an accurate estimate for sync.  It tracks both number of files and number of bytes.  Using bytes is good for big files, but if you have a lot of small files it would not be very accurate.

If you sync one big file first, and then a lot of small files, basing the estimate on bytes will say you're 99% done after the big file, even though each small file takes some time, and only 50% of the elapsed time is done.

**Comment by ppolewicz** [comment]
@clintinthecode accurate estimation of sync time is a very complex matter due to high transfer start/stop time and two highly probable network bottlenecks (on both upload and download). A disk bottleneck can also be an important factor, as it was shown in another issue (where someone has set the amount of reading threads to 200).

Accurate sync estimation was not a high priority for b2 CLI team, at least until now. Misleading estimate could be worse than nothing.

We already have some support for customizable progress reporting functionality - if you'd like to work on this, then we could help you connect your advanced estimator with the b2 CLI library. This way you could implement the progress reporting without worrying about all the stuff the CLI already does (exponential back-off after server-side failure, retrying in case of transient errors, authorization, handling tokens etc). This would benefit all parties, providing a nice interface and high quality estimation... that is, if you want to take a shot at implementing something like this. Will you?

**Comment by clintinthecode** [comment]
Hi @ppolewicz, I' mot familiar with python myself personally, but if need to have it in the future I will have one of my developers look into it and discuss further here. We are almost finished the bulk of our initial sync, maybe another week left of syncing to have it all done then from there it will just be much smaller syncs done a few times a day to backup our video server.
