### ISSUE TITLE
syncing progress speed display

### ISSUE THREAD

**Issue by nikparo** [Backblaze/B2_Command_Line_Tool#205]
I noticed a small thing that may be somewhat misleading. When using b2 sync ... the progress tracker speed seems to be an average from the whole syncing progress, or quite a long period at least, rather than the current speed.

Bug or working as intended? I for one would have expected it to be the average for the last few seconds or so, it seems to me that this is more common (and expected) in progress displays.

**Comment by ppolewicz** [comment]
Using last N seconds instead of total average is one way. Another way would be to make a solution which is kind of a bridge between what we have now and what you suggest, to get an accurate estimation:

Lets say there are two speeds: average speed and current speed.
If the user is currently occupying his network to do something short (send a 10MB email or download an ISO image, for example), then there is a good chance that the current speed will return back to the average speed soon. The chance of such thing happening decreases with the increasing time in which the current speed is being held at the same level.

We use the `tqdm` library to render the progress bars and the speed reporting, as well as ETA reporting for uploads and downloads (currently there is no ETA for sync). I think the changes to the mechanism in question should be implemented in the `tqdm` project, not in b2.

Would you be willing to take a shot at implementing the method of reporting speed, as the one you have described? We'd provide support at the B2 CLI side to integrate it when the option becomes available.
