### ISSUE TITLE
Delete files older than x days in bucket/folder

### ISSUE THREAD

**Issue by SystemZ** [Backblaze/B2_Command_Line_Tool#207]
I would like to use cron script that remove files older than x days in all file versions.
I have seen `b2 sync` command but I'm not sure if I can use it for this.
I have multiple sources of backups uploading each day to backblaze but I need to remove older files too.
Is this possible?

**Comment by ppolewicz** [comment]
Take a look at `--keepDays` option for `b2 sync`, it might be exactly what you need

**Comment by svonohr** [comment]
Note that we recently changed the behavior of the  `--keepDays N` option, so that it keeps one extra version. This allows to restore any of the fully synced states of the past N days.

For the multiple sources you can upload them to different subdirectories in your bucket. Uploading to the same destination will not work properly with the `--keepDays` option. A normal sync should work. Just deleting files older than some time could be an option for the proposed delete command (#165).
