### ISSUE TITLE
Using B2 for backups

### ISSUE THREAD

**Issue by szepeviktor** [Backblaze/B2_Command_Line_Tool#273]
A long time ago I've made a criteria list for backup software
please click here: https://github.com/szepeviktor/debian-server-tools/blob/master/backup/README.md

After going through few programs I've realizes S3QL will provide most features. It it a fuse implementation thus seems local but takes up no space on your server. It has sophisticated deduplication and encrytion.

Please consider developing a b2 backend. S3QL is also a Python project.
https://bitbucket.org/nikratio/s3ql/issues/181/add-backend-backblaze

I think most of the code is already written and needs to be organized to fit into s3ql.
Thank you!

**Comment by szepeviktor** [comment]
This is my *base* server backup script: https://github.com/szepeviktor/debian-server-tools/blob/master/backup/system-backup.sh

**Comment by bwbeach** [comment]
That's a good list of things to think about when backing up.

Would you be interested in gathering the code that's already written, and building the S3QL backend?  The (small) group of people maintaining the B2 command-line tool mostly focus on the tool itself, and not integration with other packages.

One thing that is on our roadmap is documenting and cleaning up the Python library for B2 that the command-line tool uses, so other developers can use it for integrations like this.

**Comment by szepeviktor** [comment]
> One thing that is on our roadmap is documenting and cleaning up the Python library for B2 that the command-line tool uses, so other developers can use it for integrations like this.

Thank you for your answer. Separating CLI from API implementation sounds fantastic.
It could be even another packages.
Seems like a busy project for implementing CLI from an API library: https://github.com/pallets/click/issues

```python
import click

@click.command()
@click.option('--count', default=1, help='Number of greetings.')
@click.option('--name', prompt='Your name',
              help='The person to greet.')

def hello(count, name):
    """Simple program that greets NAME for a total of COUNT times."""
    for x in range(count):
        click.echo('Hello %s!' % name)

if __name__ == '__main__':
    hello()
```

**Comment by ppolewicz** [comment]
We provide support for the API layer of our code. In fact the b2_fuse project recently switched from their own implementation of http layer to a dependency form B2 CLI, removing a large portion of their code.

The implementation of CLI is fairly clearly separated from implementation of API. I see no need to separate it any further at this time, but if there is a good reason to do it, please state it.

I don't understand why you have linked the `click` library here.

As for implementing b2 backend for S3QL and other tools (we had such requests in the past) our policy is to support it, but we won't dig into the codebase of another tool to change their code. If there is an additional function that is needed to implement such a backend in another tool and it would make sense to put this function on our side, then we are likely to add it. But since this is an issue tracker for B2 CLI, and it seems to be a S3QL issue, I think we should close it. Please open a new request if you decide to implement the support **in S3QL** and a missing function in our layer is identified.

**Comment by szepeviktor** [comment]
> b2_fuse project

Thank you for mentioning that.
It's a pitty that b2_fuse has no tests like S3QL does
https://github.com/s3ql/s3ql/tree/master/tests

**Comment by ppolewicz** [comment]
This comment is appropriate for b2_fuse repository. As far as I know, its maintainer would be happy if you would contribute to the development of his project (for example by adding tests).

**Comment by szepeviktor** [comment]
> As for implementing b2 backend for S3QL

For anyone who speaks Python:
https://bitbucket.org/nikratio/s3ql/src/c38dbbcf624c5b605a2f8b464896da6caec550b7/src/s3ql/backends/common.py?at=default&fileviewer=file-view-default#common.py-245
(I don't.)
