### ISSUE TITLE
b2 sync using all memory

### ISSUE THREAD

**Issue by robertomurta** [Backblaze/B2_Command_Line_Tool#279]
Started using b2 sync from this repository for backup of my home directory (~270G) and after not more than 5 minutes, it used all my available RAM (~10G just for b2 process, from 16G total)

I'm using Debian Jessie with python 2.7.9.
b2 command line tool, version 0.6.8

560115 itens, 473372 files

Command line:
b2 sync --threads 2 --excludeRegex '^\(VirtualBox VMs\|\.thunderbird\|\.thumbnails\|isos\)' /origin/directory b2://bucket/destination

**Comment by ppolewicz** [comment]
How did you check how much memory did it use?

**Comment by robertomurta** [comment]
I checked watching it grow on htop.
Today I wake up suspecting of circular symbolic links, since I had success on syncing on a smaller folder. I did'nt expected that b2 would follow them, but I don't know the expected behavior.
I'm investigating better here.

**Comment by robertomurta** [comment]
Confimed the simlink issue. I've created some small directories with looping symlinks and got:

`upload d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/ttt
upload d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/ttt
upload d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/ttt`

I suggest, in addition to documenting the behavior, the default was not following (somehow saving the symlinks would be cool), with flags to follow (and detecting those loops).
This issue should be closed, but another one should be created.

**Comment by ppolewicz** [comment]
I think by default b2 should follow symlinks by default. There could be a `--noFollow` flag to avoid it. Detecting circular symlinks and avoiding them would be a good thing though and a separate issue should be created for that. AWS CLI [follows symlinks by default](http://docs.aws.amazon.com/cli/latest/reference/s3/sync.html#options).

Also, You have found that two threads started uploading while a third has ran away to list everything it could until the memory was exhausted. The latter thread should stop eventually and wait the jobs are processed. In other words, the queue between the listing thread and the other threads should be bounded. Otherwise systems with a memory constraint cannot upload very large data sets.
