### ISSUE TITLE
Disable versioning

### ISSUE THREAD

**Issue by nagualcode** [Backblaze/B2_Command_Line_Tool#324]
Need a way to totally disable versioning for some buckets.
Is it possible?

**Comment by svonohr** [comment]
What excactly do you mean by versioning? If you use the sync command with the `--delete` option it will delete old versions in the bucket instead of keeping them

**Comment by droptv** [comment]
Everytime I sync/update a file, the older version of it I keeped by backblaze. I have some log files I am uploading every 30 minutes, a couple of hours is enough to make this log bucket a little monster.
Can I disable old versions of the same on a specific bucket?

**Comment by bwbeach** [comment]
There is no way to disable versioning.  But, B2 now supports Lifecycle Rules to automatically delete old versions of files.  

See: [https://www.backblaze.com/b2/docs/lifecycle_rules.html](https://www.backblaze.com/b2/docs/lifecycle_rules.html)

**Comment by droptv** [comment]
I tried leaving the life cycle as short as 1 day, or 0 day, but it isnt enought, my bucket gets so huge it crashes the browser and third party clients like cyberduck.

**Comment by bwbeach** [comment]
Setting to 0 days is not allowed.  And I'm afraid that 1 day is the best there is.  

I'm surprised that Cyberduck crashes.  It should be able to handle *lots* of files.  How many files are there?

When you say the browser crashes, is that the backblaze.com web site?

**Comment by droptv** [comment]
I have some 30 remote machines updating theier log files every 20~30 minutes, each file endup with 100 versions.  
Firefox always crashed when trying to view the contents of the such buckets. 
The same with cyberduck. 
As of now I am manually purging the bucket to keep it sane.
Searching google I found that users of NAS machines with backblazed are also having problems with versions.
It would be nice if it could be turned off for some buckets.

**Comment by bwbeach** [comment]
30 machines times 100 versions is only 3000 files.  The browser and Cyberduck should easily be able to handle that.

We have tested with hundreds of thousands of files.

Because this is not an issue with the command-line tool, I suggest you contact the [Backblaze help desk](https://www.backblaze.com/help.html) (see the Contact Us links at the bottom of the page).

**Comment by droptv** [comment]
Firefox crashed and cyberduck returned network error, until I purged the bucket.
Yep, it was more a feature-request for the command line, to be able to turn of versioning for a bucket.
I will send to request to help desk.
Thank you.

**Comment by svonohr** [comment]
Whats wrong with the `--delete` option I suggested? The only problem I see is that you need a separate folder for each machine. Maybe we should extend the sync command that it can upload single files?

**Comment by droptv** [comment]
yes the script to upload the logs can create a folder and sync --delete to that folder, that is a workaround.
Anyway I would keep the "disable versioning" feature request too.
Thank you.

**Comment by ppolewicz** [comment]
@droptv could you please explain how the sync with disabled versioning would work? While it may be obvious to you, it is not clear to me. Do you mean that, when syncing, if a file with the given name exists on the remote location, then the new version is uploaded and the old one is deleted? And if a file exists only on the remote location (as if, it was uploaded to the same directory by another machine), it should be kept. Is my understanding correct? Is there any detail that I missed?

**Comment by droptv** [comment]
Yes. Btw, I am using rclone tool (rclone.org).
folder1/file1.txt  --> b2bucket/file1.txt
when I copy or sync folder1 to b2bucket ,  this file1.txt should be overwriten .
If another machine has folder1/file2.txt and sync with --delete option to b2bucket, file1.txt would be deleted... But I can always "copy" instead of sync with --delete.
As of now all my machines "copy" theier log file to the root of b2bucket. The log file name is the machine name. So I expect all the log files to co-exists inside the root of the b2bucket. I would prefer that when a log file is uploaded it would overwrite the old file with the same name, remaning only actual log file, and no old versions of it.

**Comment by ppolewicz** [comment]
B2 is an object storage where objects are immutable, so it's a bit different than in case of rsync that deals with filesystems, where the same file can be overwritten.

But I get what you need.

**Comment by bwbeach** [comment]
How about making a folder for each host to sync to.  Then you could sync with `--delete` and only affect the files from that host.

**Comment by droptv** [comment]
Yes, that is exactly the idea of @svonohr. It works.
Still, it would be a nice feature to be able to disable versioning / imutable files.  If B2 system works in such a way it is impossible to change this behavior, at last be able to make old versions really ivisible, hide it from the user. It is not only me.
Least, B2-Cloud is working great, it is a great product, keep it up.

**Comment by ppolewicz** [comment]
Actually, this feature is a good assignment for a new contributor. @droptv, are you by any chance interested in contributing some code to this project?

**Comment by droptv** [comment]
I would love, but I am still make my way learning basic bash

**Comment by craSH** [comment]
Hi, I'd like to see if this issue could get some attention again - I have basically the same issue, and would like to disable versioning for a bucket entirely.

I have a script that uploads a file called `live.jpg` to a b2 bucket approximately every 5 seconds - that happens to be a frame grab from a weather camera. Most services that can consume webcam feeds even in 2019 are based on periodically polled images, many even expecting you to upload them via FTP. I felt like using b2 for this was a decent option, and it actually works great.

However, even with global bucket lifecycle settings set to "Keep only the last version of the file", using the `backblaze-b2 sync [...]` command with any variation of related arguments cause multiple versions of the file to be retained.

I understand that `--delete` is an approach that can be used to remove the versioned files, but given the bucket setting I would not expect this to be necessary (e.g., it should not create versions in the first place). The approach of using `--delete` is not suitable in my case, because it is not an atomic delete - there is in fact a period of time during the run of the b2 sync operation where the file is not present, before the new version is uploaded by the sync operation. That is not acceptable for my use case (services/users hitting my webcam feed can, and do, get a 404 error if they hit it at the right moment).


For reference, here is how my script invokes the backblaze-b2 sync command, every 5 seconds, running on an Ubuntu 18.04.2 LTS system:

`backblaze-b2 sync --noProgress --replaceNewer --compareVersions modTime /tmp/wx-webcam-uploader/KWASEATT416-Cam-SE b2://cdine-webcam/KWASEATT416-Cam-SE`

Adding an explicit `--keepDays 0` has no effect, as mentioned previously in this issue. Setting it to 1 (or setting the global bucket settings to 1 day) is also not desirable, as it does indeed make the web UI for the backblaze.com bucket files page quite slow (even a day will end up having around 17280 versions present) - but the real thing that I'd like to avoid is paying for those versions. My use case does not need past versions in any way.

**Comment by ppolewicz** [comment]
Your usecase is very specific. I think you should do it in a following way:
* have one script that uses `b2 upload-file /tmp/wx-webcam-uploader/KWASEATT416-Cam-SE/live.jpg b2://cdine-webcam/KWASEATT416-Cam-SE/live.jpg` every 5 seconds
* have another script which makes a list of file versions in that directory and deletes all except the most current one every 6 hours. Set `maxFileCount` to `1000`.

So it's 2 lines of code to put in the crontab, one of them long-ish. It can be further optimized by storing the file-id's when the upload is performed to skip getting a list of files to delete (and save some transactions), but it can cause a leak in a corner case related to network issue, so you'll need a cleanup script anyway (though in such case it can be ran infrequently).

While it would be nice to have a service-level option to disable versioning completely, judging by the activity in this issue here and the easiness of delivering the functionality in bash, I would say that implementing it, testing it, documenting it and supporting it is not on top of the priority list for a good reason.

**Comment by ppolewicz** [comment]
Since this issue cannot be implemented in the CLI for the reported use case with a reasonable cost (as frequent listing of a bucket is not free, so in order to amortize that cost, it has to be a separate (or cached) operation and not a part of file upload) and there is no support for version-less buckets in the B2 service, this issue is inactionable, so I'm going to close it. If some new information comes to light one day, please open a new issue, describe your use case and reference this one.
