### ISSUE TITLE
[enhancement] Copy, modify file

### ISSUE THREAD

**Issue by billouboq** [Backblaze/B2_Command_Line_Tool#339]
Hi, I'm using B2 as a replacement for dropbox and I was wondering if b2 will soon have a copy and modify api http endpoint. Because at the moment you can't rename a folder or a file and you can't put files in an other folder so it's kinda hard without those two functionalities.

PS : the only way to do the two, is to delete and create a new file with the name I want, but if I want to copy files from a folder to an other, it's much more complicated since I have to re-upload all the files in an other 'created' folder and delete the old folder when it's done. And since B2 doesn't have a delete multiple files api, we have to delete all files one by one...

**Comment by ppolewicz** [comment]
@billouboq thank you for your interest in B2.

This is an issue tracker for B2 CLI, not for the B2 service itself. The appropriate place for the type of feedback you want to give, is b2contact@backblaze.com

While it would be imaginable to implement a special type of bucket which would allow for movement of files, it is a lot of work and it carries a performance penalty, synchronization issues etc. We have actually designed the primitives required for implementing this, but I am not sure if mainline repository is the right place to store such customized implementations, unless we would expect them to be widely adopted. Since this request is very rare, I wouldn't expect many users to be interested in that. Therefore it only makes sense if the server side implements it, which maybe they could do, but in order to discuss that, you really need to email the people that are responsible for B2 API (they don't read the B2 CLI issues).

**Comment by ppolewicz** [comment]
Duplicate of #57
