### ISSUE TITLE
b2 get-bucket size info

### ISSUE THREAD

**Issue by lmbss** [Backblaze/B2_Command_Line_Tool#404]
Hello, 

It would be interesting to get-bucket command to have all the information on the web, the size and number of files being the most important missing

Best Regards

**Comment by sebi707** [comment]
Currently the `get-bucket` command just uses the [`b2_list_buckets`](https://www.backblaze.com/b2/docs/b2_list_buckets.html) API call, which does provide such information. To get the number of files and size one probably has to list all files, which may require many API calls if there are lots of files in the bucket.

**Comment by ppolewicz** [comment]
@lmbss "it would be interesting" means that you would actually use it if it was available, or just that it would be nice to have? What would you use it for?

I am asking because b2 is out for quite a while now and nobody ever came with justification to implement this. Perhaps you are the one!

**Comment by lithium3141** [comment]
I'd love to see this implemented as well. I couldn't find anywhere in the API where this kind of summary data is exposed (beyond listing every file in a bucket and tallying sizes), but think it could be useful for:

* Custom reporting or "dashboard" visualization, including graphing trends over time
* Monitoring systems beyond the alerts Backblaze delivers (e.g. "alert if bucket X grows too quickly")
* Locally-enforced "soft caps" for uses where — for whatever reason — a bucket should not grow too large

I personally would definitely use a "total size of bucket" API call or feature for the reporting aspect, since I'd love to see bucket size info as part of a larger dashboard without having to log into the Backblaze Web control panel.

**Comment by jamieb22** [comment]
We need this function too!

**Comment by toddATavail** [comment]
I am about to issue a pull request to address this feature request. I have added an option, `--showSize`, to `get-bucket` that adds two new fields to the output:

* `fileCount`, which is the count of all files in the bucket
* `totalSize`, which is the aggregate size of all files in the bucket

I have added appropriate help text (available as *b2 get-bucket --help*).

Example usage:

```
b2 get-bucket --showSize <bucket>
```

Omitting `--showSize` performs the original behavior. Note that `--showSize` entails addition API calls, and therefore additional latency and computation.

**Comment by bwbeach** [comment]
Looks good.  One final issue to think about: What does "bucket size" mean?

B2 supports [file versioning and hiding](https://www.backblaze.com/b2/docs/file_versions.html).  What should the answer be if there are multiple versions of a file, or if a file is hidden but still using space?

`Bucket.ls` has options for showing all file versions.

Also, in the doc string, it's probably worth mentioning that `--showSize` will list the files, and incur transaction costs for doing so.  That will avoid having customers call support when they see a bill for lots of calls to list files.

**Comment by fabiospampinato** [comment]
Is there any plan to update the API anytime soon? I see a commit has been made ~2 months ago, but the cli app hasn't been updated since november of last year (!).

I also wanted to add this information in my private dashboard, it was literally the last point of my todo list, and I'm kinda disappointed there's no support for this yet.

**Comment by bwbeach** [comment]
There are no immediate plans to add an API to get bucket size.

I do plan to release the command-line tool in the next couple weeks, with this change.

**Comment by fabiospampinato** [comment]
@ppolewicz It does, but I want to show that info in my custom dashboard, I don't want to keep backblaze's tab around just for this.

**Comment by ppolewicz** [comment]
What I meant was... instead of issuing a massive number of API requests, an alternative solution would be to parse the information out of the admin web panel. Fast & free. `requests` or `mechanize` and `bs4` should make it easy.

In my mind, that would still be better than brute-forcing it out to get a simple bucket size. It's an O(N) vs O(1) thing, for a petabyte-capable storage... Plus it is easily fixable in a minor version, when b2 api exposes that capability.

If memory serves me, this was a problem from day one. Upon beta release of b2, this kind of metadata was already available in the web panel and not visible in the API.

**Comment by fabiospampinato** [comment]
@ppolewicz I don't think anybody is trying to compute the bucket size of large buckets on his own using the current API, precisely because it would be an expensive operation. 

Sure, I could extract that info from the website, but:
1. APIs are there for making things easier/more reliable. I want to use the actual APIs, not scrape websites, maybe one day you'll change the markup of the page or something and my code will break.
2. In order to scrape the website I have to provide my application with full access to it, I would rather prefer to use a custom API key with limited permissions, for security reasons.

**Comment by raindog308** [comment]
Yes, I could write a requests/mechanize script to scrape the Backblaze account info page...and it'd break every time they change it.  I remember that technique from, oh, 1995...

That's kind of the point of APIs.

This info is really needed because asking what size a bucket is (and how many files it has) is a pretty basic operation.  Personally I'd like to compare my local sizes to what's in the cloud to make sure things succeeded.  Proactive checks.  It's a pro thing.

Also, for non-backup buckets I'd also like to chart/graph usage over time...need data for that.

Etc.

**Comment by andrelec1** [comment]
no more new ?

**Comment by TowerBR** [comment]
I gave up - a long time ago - to wait for a solution to this by B2 CLI, and implemented a set of scripts using [Rclone size](https://rclone.org/commands/rclone_size/) that generates CSV's. Very easy.

**Comment by ppolewicz** [comment]
What's the difference between `rclone size` and `b2 get-bucket --showSize <bucket>`?

**Comment by TowerBR** [comment]
Simple, `rclone size` works and it's fast (considering  the [#455](https://github.com/Backblaze/B2_Command_Line_Tool/issues/455) issue mentioned above).

**Comment by ppolewicz** [comment]
I'm curious, what's the actual difference in execution time on an example bucket using both tools?

**Comment by FrozenBeard** [comment]
Is there a way I could grep just the totalSize? I cant seem to get it to work :(
(I'm absolutely terrible with regEx and using random examples from StackOverflow) 
Trying this;
`backblaze-b2 get-bucket --showSize PirateCraft | grep -Po '"totalSize":.*?[^\\]",'`

**Comment by ppolewicz** [comment]
Parsing json with regex is a bad idea, might lead to errors when filename is similar to the key etc.

**Comment by FrozenBeard** [comment]
What I have dousnt work ☹️

**Comment by ppolewicz** [comment]
@FrozenBeard 
```
backblaze-b2 get-bucket --showSize PirateCraft | jq .totalSize
```

**Comment by ppolewicz** [comment]
I'm closing this issue now, since it's not actually a problem with b2-cli.
