### ISSUE TITLE
b2 sync changes file names with accents and latin characters on macos

### ISSUE THREAD

**Issue by jmfederico** [Backblaze/B2_Command_Line_Tool#430]
I am using version 1.1.0 on a MacOS 10.13.3

I have a bucket which I synchronized a while ago, and today I was about to sync again, and noticed that the list of changes that were going to be performed was larger than I expected.

The problem is with files or paths with accented characters or with n "ñ" on them.

Situation:

Remote file (in bucket)
 - /path/accénted/file.foo

Local file
 - /path/accénted/file.foo

Changes to be performed by b2
 - delete /path/accénted/file.foo
 - upload /path/accented/file.foo            s

So b2 is removing the accent from the file/path and tries to find a remote file that matched the modified name, which fails, it then finds the accented file remotly and decides that locally it has no counterpart, so deletes the remote on, and uploads a new one.

Now, the "upload" action has an "s" at the end, which I do not know what it means.

Now, I tested on a new accented file, one that did not exist on the bucket, and it uploads fine, keeps the accent, and subsequently correctly detects that the file exists already, so this seems to be happening with only the old files I have.

**Comment by jmfederico** [comment]
I just tried with a docker container mounting the files as a docker volume, and it does the same. SO is not Mac OS specific.

**Comment by bwbeach** [comment]
Unfortunately, it works for me, as it did for you when you re-tested.  It's going to take some digging to figure out what's wrong.

```
$ find . -type f
./path/accénted/file.foo
$ b2 sync . b2://bwb-test
upload path/accénted/file.foo                                      
$ b2 sync . b2://bwb-test           
$ touch path/accénted/file.foo 
$ b2 sync . b2://bwb-test
upload path/accénted/file.foo                                      
$ b2 ls bwb-test path                        
path/accénted/
$ b2 ls bwb-test path/accénted
path/accénted/file.foo
```

I assume you've verified that the file names on your local filesystem to make sure they are still correct.

As a test, it might be worth syncing just that folder to a different place in B2 and seeing what file names it comes up with.

**Comment by svonohr** [comment]
> Now, the "upload" action has an "s" at the end, which I do not know what it means.

There should be no "s" at the end, only the filename and path it's about to upload. So somehow b2 removed the accent and put a space and "s" at the end of the filename. From your general error description I would have suspected an encoding problem, but the apparent corruption is really strange.

**Comment by jmfederico** [comment]
I think I know what is going on, but don't know how to test it.

Reading https://stackoverflow.com/a/6153713/2966465 it seems to me that since I upgraded, names were changed locally by Mac OS, but on the server they use the old encoding. So, any new file I upload will have the new encoding, but old files will differ, they have different filenames because Mac OS renamed them all with a new encoding.

Is this something that python or b2 should handle?

**Comment by jmfederico** [comment]
HFS normalized names, but APFS does not. Will that have something to do with all this?

https://eclecticlight.co/2017/04/06/apfs-is-currently-unusable-with-most-non-english-languages/

When I first synced, I think I did it when my mac was running on HFS (don't really remember)

**Comment by svonohr** [comment]
Interesting. I haven’t heard of this until now. Seems like something that could be handled by B2 CLI. But I don’t know what the best solution is here. Choosing one of the normal forms as the default and converting all names on upload to this form will probably break existing synced directories and require lots of reuploads. Maybe add an option which recognizes filenames as equal regardless of their form? This seems certainly better but I don’t know if this is even possible in all cases.

**Comment by jmfederico** [comment]
If you have a suggestion on how I can handle this even if temporarily, I would appreciate it.
There is just too much data that seems out of sync, and it would take me a while to re-sync.

Cheers

**Comment by bwbeach** [comment]
Thanks for the pointers to the docs.  I didn't know about normalized form of Unicode before.  I think it would make sense to add a `--normalizeUnicode` option when syncing, so that the destination files are always in normalized form.  We would have to decide what to do if there are two source files that have different names, but normalize to the same name.

I'm not sure this normalization is the problem you're seeing, though.  It doesn't explain dropping the accent, or adding the "s" at the end.

**Comment by bwbeach** [comment]
Does the "s" show up when you `ls` the files from the command line?

**Comment by jmfederico** [comment]
About dropping the accent, setting LANG and LC_ALL fixes it, it was just and output issue, it was being uploaded with the accent.
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

**Comment by svonohr** [comment]
After reading some more about unicode equivalence I would favor a solution where filenames are compared normalization insensitive. From what I’ve read this should be possible by converting to any of the normal forms and comparing the output. When the destination file does exist the file is uploaded using the same normalization as the existing file. This way it can be compatible with older B2 CLI versions and other clients. I think this should even be the default option, since the number of users who have files with different normalization and actually want this handled as two separate files should slim to none.

**Comment by jmfederico** [comment]
Just to be completely sure that it was a naming issue, I run this python script:

```python
from unidecode import unidecode

upload = set()
delete = set()
other = set()
# Output from
# b2 sync --noProgress --dryRun --delete --replaceNewer /path  b2://path 1>>! b2-diff.txt
with open('b2-output.txt') as f:
    content = f.readlines()

# Normalize filenames
for line in content:
    if line[:6] == 'upload':
        upload.add(unidecode(line[7:].strip()))
    elif line[:6] == 'delete':
        delete.add(unidecode(line[7:].strip()))
    else:
        other.add(unidecode(line[7:].strip()))

# Get difference between upload and delete lines.
# Files that were changed will have "(old version)" appended to them,
# so will show in the result.
final = upload.symmetric_difference(delete)

# Give me the results!
with open('diff.txt', 'w') as sortedF:
    sortedF.write("\n\n DIFF \n\n")

    for line in sorted(final):
        sortedF.write(f"{line}\n")

    sortedF.write("\n\n OTHER \n\n")

    for line in sorted(other):
        sortedF.write(f"{line}\n")
```

And the output was the one I expected:
 - It had new and changed unaccented files.
 - If had new accented files.
 - All changed accented files were not present.

**Comment by bwbeach** [comment]
I like the idea of normalization-insensitive ordering, @svonohr.  

Getting a list of files in normalized order from the local file system would be straightforward.  The code is already sorting the names in each directory following the B2 ordering conventions.

Files named `Ω` (omega) and `Ω` (ohm sign) would not be next to each other in sorted order, and could have an arbitrary number of files between them.

The current algorithm is to walk through the source and destination files in order, comparing.  I'm not sure how you would do that without getting a list of all files in B2, which may not fit in memory, and then sorting it.

**Comment by bwbeach** [comment]
Is your immediate problem solved, @jmfederico ?

**Comment by jmfederico** [comment]
Unfortunately no.
I just confirmed that I still have a problem.

**Comment by svonohr** [comment]
> The current algorithm is to walk through the source and destination files in order, comparing. I'm not sure how you would do that without getting a list of all files in B2, which may not fit in memory, and then sorting it.

That's a good point. I don't know how to solve it. Then it's probably an easier solution to just normalize names on upload, but have some choices so users can use the same normalization of what's already in the bucket. What further complicates things is that HFS+ uses a variation of NFD which does not decompose all characters.

**Comment by bwbeach** [comment]
On the whole, I think the current behavior is correct: Syncing uses whatever names you have in your file system.  That way, if they are synced back from B2, they will have the same names they started with.  Some people may care which version of a name they have.  As a default behavior, I think this is correct.

Case-insensitive syncing is difficult, for the reason I mentioned before: generated the names in B2 in a consistent order requires re-sorting the whole list if they're not stored in that order.  I don't want to have to download the full list of files in the bucket and then sort before starting the sync.

The question then is whether there should be an option to normalize on upload.  It can normalize the local file names, sort in that order, and then sync as usual.  In what cases would this be useful?

My guess, @jmfederico, is that when you converted from HFS to APFS the file system stopped normalizing names.  Then when you updated the files, they wound up getting renamed to non-normalized names.  (Were the files in question updated before this problem showed up?) Because the file system is normalization-insensitive, you don't have both names.  So when it syncs, it's going to upload the new version and hide/delete the old one.  This seems like exactly what it should be doing.

**Comment by svonohr** [comment]
I just played around with unicode normalization on windows and linux and they both preserve whatever normal form I use. They are also not normalization sensitive and I can have both normalizations next to each other. So I also believe that B2 CLI currently does the correct thing.

From what I’ve found online it seems that HFS is the only filesystem which actually does perform normalization. So it could be useful for users coming from HFS to have an option to force the old normalization. This would be an option for a very specific use case and I don’t know how many users will actually run into this problem.
