### ISSUE TITLE
B2 waits until after upload is complete to check for account data

### ISSUE THREAD

**Issue by kaysond** [Backblaze/B2_Command_Line_Tool#445]
My script that uploads to backblaze recently started failing silently. In my logs, I found the following:

```
URL by file name: https://f002.backblazeb2.com/file/*******
URL by fileId: https://f002.backblazeb2.com/b2api/v1/b2_download_file_by_id?fileId=4_z151ddf3e3de674a46a320710_f200f51911f5f6bf7_d20180610_m094632_****
{
  "action": "upload",
  "fileId": "4_z151ddf3e3de674a46a320710_f200f51911f5f6bf7_d20180610_m094632_****",
  "fileName": "****",
  "size": 8060512200,
  "uploadTimestamp": 1528623992000
}
ERROR: Missing account data: 'NoneType' object has no attribute '__getitem__'  Use: b2 authorize-account
```

Only after the upload was finished did b2 check for the account data and throw an error. This means that it wasted hours uploading the file, only for it not to work. Not sure how the account data got corrupted but it would be nice for the check to happen before the upload.

**Comment by ppolewicz** [comment]
After further consideration, this is a very environmental issue. Account info was fine when the upload was started and got corrupted before the large file upload was completed. The fix for that would be to copy the database into memory (in fear that someone is going to break it while we are running), but that's not impractical. The user of any program generally cannot expect it to work while the configuration file is being corrupted.

**Comment by kaysond** [comment]
@ppolewicz is that accurate? If the account information is valid and gets verified before the upload starts, why does it need to be checked again after the upload is completed? If it does need to be checked again, it already exists in memory because it was read from disk at the beginning. There's no reason to hit the disk again...

I'm quite certain that the account info was corrupted before the upload began, it just wasn't checked.

**Comment by ppolewicz** [comment]
I'm pretty sure the server wouldn't let you upload files without proper authorization - otherwise you could just upload files into buckets of other people and that is not the case.

You had to be properly authorized in order to begin the large file upload. Later when the upload was being finalized, config was already corrupted.

`SqliteAccountInfo` (used by the CLI) does *not* cache the authorization token in memory. Maybe it could.
