### ISSUE TITLE
Executable name b2 clashes with b2 from Boost.Build

### ISSUE THREAD

**Issue by WPettersson** [Backblaze/B2_Command_Line_Tool#447]
The entry point b2 in setup.py means the file /usr/bin/b2 is installed by this project. However, Boost.Build also installs a file called /usr/bin/b2. Is there any open discussion for changing this name? For the record, I have changed it on my end (calling it b2_bb) so it doesn't clash, but I want to know whether it's worth me making a PR for this issue as well, or whether you are happy to clash with Boost.Build and don't want to rename the file.

**Comment by ppolewicz** [comment]
The project is on github since November 2015 and, as far as I know, nobody reported this as a problem so far. Things will clash with each other inevitably, especially if they are short and convenient to execute from a command line. (shouldn't your build environment be stored in a `chroot` anyway?)

I don't think we should change the name of the console command for all existing b2 CLI users just because once in a few years someone has a collision. You said yourself that you have applied a workaround, I suspect this is easy for others affected by this particular collision, given the fact that they have Boost.Build installed.

Do you think we should rename it? Why?

**Comment by WPettersson** [comment]
I was just curious, mostly. If it was going to be a rename, it'd be a lot of work so I'd volunteer to help. It sounds like it's not going to be a rename since it is so rare, so I'll just keep my personal patch to myself. I haven't yet decided whether I stick to b2_bb, or whether I just drop the entry point entirely, I only wanted the python package for another script anyway.

**Comment by kevincox** [comment]
Note that there are multiple distributions that change the name of the package. In fact this list includes Ubuntu which is the most popular so it is likely that many users use a different name.

* https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=backblaze-b2
* https://github.com/NixOS/nixpkgs-channels/blob/1179840f9a88b8a548f4b11d1a03aa25a790c379/pkgs/development/tools/backblaze-b2/default.nix#L34
* http://manpages.ubuntu.com/manpages/bionic/man1/backblaze-b2.1.html

I haven't checked any others.

I understand if you don't want to change the default but it would be nice if it there was support for maintainers to do this. I am aware at least two points of difficulty here:

* Error messages hardcode the `b2` name.
* The bash completion script hardcodes the `b2` name.

**Comment by mlech-reef** [comment]
Hi!

I've made an update to get the executable name dynamically as part of #658.
As far as to bash completion, it's not used by any maintainer yet and hasn't been updated for quite a time. We'll follow up in separate PR

BR/ Maciej Lech

**Comment by kevincox** [comment]
Thanks, that's a nice improvement already. I look forward to seeing the completion scripts updated too.
