### ISSUE TITLE
unable to authorize account: ClockSkew

### ISSUE THREAD

**Issue by IanS5** [Backblaze/B2_Command_Line_Tool#449]
I'm getting the error `ERROR: unable to authorize account: ClockSkew; local clock is 3591 seconds ahead of server`.

I'm running 64bit linux, distro is arch. 
`uname -a` reports `Linux ian-pc 4.17.2-1-ARCH #1 SMP PREEMPT Sat Jun 16 11:08:59 UTC 2018 x86_64 GNU/Linux`.
 `hwclock` reports `2018-06-21 16:17:46.389044-04:00`
 `date` reports `Thu Jun 21 16:18:19 EDT 2018`.
Googling time gives me `3:19 PM Thursday, June 21, 2018 (EDT)`
(the times may be changing slightly I'm getting all this info while writing this)

Sorry if this isn't an issue with the B2 CLI, but I can't find any inconsistencies in the time on my system.

**Comment by certainmagic** [comment]
>
> date reports Thu Jun 21 16:18:19 EDT 2018.
> Googling time gives me 3:19 PM Thursday, June 21, 2018 (EDT)


i might be misreading this, but....it looks to me like the time on your
system is about an hour ahead of the time google thinks it should be (4pm
vs 3pm).  that's consistent with what the b2 command line client is saying
("local clock is 3591 seconds ahead of server"), since 3600 seconds is an
hour.

can you compare the time on your machine to the actual time where you are
again?

ttfn,
ab

**Comment by IanS5** [comment]
Wow I'm really dumb. That was it. thanks for helping me out with this :+1:
