### ISSUE TITLE
`get-bucket` with `--showSize` is so slow that's useless

### ISSUE THREAD

**Issue by fabiospampinato** [Backblaze/B2_Command_Line_Tool#455]
There was an issue somewhere about retrieving the size of buckets via the API/CLI app, I can't find it anymore, did you guys delete it?

Anyway I see in v1.2.0 an `--showSize` option has been added to `get-bucket`. But it's implemented in a way that makes it totally useless for me. I have millions of files in my buckets and it takes forever for `b2 get-bucket --showSize my-bucket-name` to complete, rendering it unusable.

It should instead return the cached value you guys are using in the web app, and that value should of course be reasonably up-to-date. Recalculating this value every time I run that command, if that's what's happening here, seems like a complete waste of time to me.

I would love to be able to add some useful information about my b2 buckets into my private dashboard without having to scrape the website, as recommended by somebody.

Can you guys fix this please?

**Comment by svonohr** [comment]
The issue you mean is #404. Currently there is no way to retrieve the cached value from the B2 web interface using the API.

**Comment by andrelec1** [comment]
For my projet, i have bunch of automate that sending me lot of csv...
Before making any treatement on the files, i backup each file in bucket 
(i need to keep the raw original file for legal reason...) 
I make a little monitoring app that show me the bucket size ( refresh every 10 minutes )...
I implemente a little 'alert' feature... if the file number didn't incremente in x time then the backup solution is KO ( and the rest of the solution too)...

For the moment i have only 1 automate on this backup solution 
my buket count 14k files for 20mb ... 
80% of my request api is b2_list_file_versions ...

The number of files in the bucket is going to grow exponentialy 
So this is not a long terme solution :/

I think we realy need a official solution for getting this information ... 
Or making a little hack for reading this information directly on the webpage :/

**Comment by TowerBR** [comment]
I gave up - a long time ago - to wait for a solution to this by B2 CLI, and implemented a set of scripts using [Rclone size](https://rclone.org/commands/rclone_size/) that generates CSV's. Very easy.

**Comment by ppolewicz** [comment]
As we've found in #404, `rclone size` does the same thing as `get-bucket --showSize` under the hood.


This is not an issue with b2 command line tool, but with b2 server and so the feature request for it should be communicated to Backblaze support, not on b2-cli issue tracker... unless someone can find any way for us to speed up the current implementation (in that case, please post your idea here and we'll reopen the issue).

**Comment by andrelec1** [comment]
Well, last time i ask to the support , they redirect me here ...
After more than 1 year without any official response its maybe time to someone with 'grade' ask to the support, because simple customer can't do anything than juste complaigne of this lacke in the api ...

**Comment by ppolewicz** [comment]
I'm sure that this is on the list of their priorities, it just doesn't happen to be on the top of it. The amount of traffic in this ticket kind of confirms that getting the file size in an instant is not a highly demanded feature, so perhaps the server team is right to prioritize other things (such as the recently added server side copy, which I personally think is way more valuable than fast&cheap bucket size).

If there is a good reason why fast size should be added, providing a justification for it might increase the priority... but I can't see anything like it. For anything that I can imagine, quick access to bucket size is just not very important.

**Comment by fabiospampinato** [comment]
@ppolewicz Honestly your comment makes no sense at all to me, I don't want to sound rude but I'm somewhat upset at the moment.

> The amount of traffic in this ticket kind of confirms that getting the file size in an instant is not a highly demanded feature

> quick access to bucket size is just not very important.

Why don't we test that hypothesis, try to remove the size of buckets from the web interface and let's see if people complain about it 🤦‍♂.

By the way the most upvoted comment in the [previous issue](https://github.com/Backblaze/B2_Command_Line_Tool/issues/404#issuecomment-389192210) about this has got as many upvotes as the most upvoted currently open issue on the repo. If I may suggest a few possible reasons why you folks aren't seeing "enough traffic" here (btw how are you measuring how much traffic issues receive?):

- Instead of listening to user feedback we've been told to scrape the website for this information, jeez. Understandably after answers like this the will to contribute to the discussion by posting another comment jumps off a cliff.
- Multiple issues have been opened about this already and they have been closed without the issue being resolved, with reasons like "This is not an issue with b2 command line tool, but with b2 server", well, where's the b2-sever issue tracker? And who even cares about that, I'm interacting with b2-cli and that should provide the feature, if under the hood that requires some modifications in other parts of your stack that doesn't mean this is not _also_ an issue with b2-cli.

> If there is a good reason why fast size should be added, providing a justification for it might increase the priority...

Should I link to all comments pointing at very good reasons? Let me list a few:

- [Very first comment on this issue](https://github.com/Backblaze/B2_Command_Line_Tool/issues/455): I have millions of file and the command takes forever to execute, plus I want to show the bucket size in a custom private dashboard.
- [Very first comment that answered this same question already in the previous issue](https://github.com/Backblaze/B2_Command_Line_Tool/issues/404#issuecomment-364759610): private dashboard, custom monitoring system, soft caps.
- [Most upvoted comment on the previous issue](https://github.com/Backblaze/B2_Command_Line_Tool/issues/404#issuecomment-389192210): not having to scrape websites like it's 1995 and have the thing break with every change in the UI.

From time to time I try to replace the worst programs I currently depend on with better ones, I guess B2 might be next in line for me.

**Comment by ppolewicz** [comment]
I am involved in the CLI project for the last three years, mainly because backend software development is a passion of mine, not because I am a Backblaze employee. I barely have any connection to the server team - I don't know how large it is, who's on it and I don't know what they do until I see the blog post. Nevertheless, I'm trying to help you as much as I can.

**The correct way of posting feedback for the b2 server is through b2 support email box**. I wish that there was a github issue tracker for this too, but that's not how it is currently organized and so some server-side issues are overrepresented on the cli issue tracker and some are underrepresented. I am pretty sure that support, being the designated place where server issues should be reported, has a much better view on the demand of server-side features than we ever will. From what I understand, as with any SaaS product, someone is analyzing the feedback situation continuously and is re-prioritizing the backlog of work. The comment you have linked, has 9 upvotes. It's impossible for me to say how that relates to the number of B2 customers, but I guess that's just a tiny fraction and that other issues (such as server-side copy file) will be used by way more users than that.

If getting cheap and fast feedback about bucket total size is something that is essential to your workflow and a web-panel workaround won't work for you, then I'm afraid that, as of today, B2 might not be the perfect solution for your application. As soon as the API of the server changes, I'll by super happy to add it to the b2sdk and B2CLI, but until that point, there is not much that I can do for you, other than to point you to b2 support and try to convince the server team to easy access to bucket size.

**Comment by fabiospampinato** [comment]
> but I guess that's just a tiny fraction

Of course, I don't expect any meaningful percentage of the costumer base to browse this issue tracker, read all the issues, read all the comments, and upvote the ones they care about.

If your point is that upvotes may not be enough for prioritizing issues in this repository I may agree with that, but then what makes you say this problem hasn't received enough "traffic"?

> there is not much that I can do for you, other than to point you to b2 support and try to convince the server team to easy access to bucket size.

Fair enough, it feels a bit weird that I should be contacting the server team rather than you forwarding them these feedbacks or them joining the discussion here but ok, but if there's nothing you can do about these sorts of issues I would strongly recommend you to close these kinds of issues immediately, don't ask questions if the answers to them won't change a thing anyway, I feel like I just wasted some time joining the discussion here.

> and that other issues (such as server-side copy file) will be used by way more users than that.

Maybe, I have no idea how many people requested that to the support team, if they're even keeping track of these things. What seems to be the [related open issue](https://github.com/Backblaze/B2_Command_Line_Tool/issues/160) here has 0 upvotes so I don't know, maybe that feature and all the other things that have been implemented in the past year or so were really way more useful 🤷‍♂

**Comment by phillmac** [comment]
@bwbeach is there any update on this? 
It's a pain in the ass having to tab to the webpage and refresh rather then having something I can use in a tmux window with the `watch` command along side my transfer progress.

**Comment by ppolewicz** [comment]
I don't understand. Why isn't the cli progress reporter enough? Client knows exactly how much it sent and it presents this information to the user

**Comment by phillmac** [comment]
I'm asking if there's any updates to the server side api, hijacking this a little since it seems to be one of the very few ways to communicate with the engineers. 
And no, I want the total size of the bucket, not the progress of the current job.
The current job is overwriting some existing objects, sometimes with duplicates, sometimes not and uploading completely new objects. 
What I want to monitor in as close to real-time as possible is "what's the ratio of the bucket size before the start to what it is currently" so I can monitor when the job starts uploading new files , at what point has the previous job progress been exceeded?
The job is uploading files from a deduplicated ipfs data store so subsequent jobs might upload the same contents again, but there will only ever be one copy in b2 due to the lifecycle rules of the bucket and ipfs' internal dedupe engine.
I want to observe the growth of the bucket  before, after and during jobs. Some jobs might upload hundreds of gigabytes but because of the dedupe the net change in the size of the bucket is zero.
Having to recount millions of objects renders the exercise impossible.
