### ISSUE TITLE
Date Problems After Software Upgrade

### ISSUE THREAD

**Issue by GlitterCakes** [Backblaze/B2_Command_Line_Tool#528]
I recently upgraded the version of the b2 sync software to the latest, don't ask me what the previous version was I can't remember. Well now when I run the sync command it tells me that there are newer files in backblaze and that I have to use --replaceNewer which is simply not true. The files in backblaze are NOT newer and I do not wish to waste time reuploading these files. What is going on? There is no technical error for this just the program simply stating what I said above.

**Comment by ppolewicz** [comment]
Please run the sync with [debug logs enabled](https://github.com/Backblaze/B2_Command_Line_Tool#detailed-logs), it will say exactly what the problem is.

**Comment by bwbeach** [comment]
This is the unfortunate result of a bug fix in the last release, which in retrospect should have waited for the next major release number.  It only shows up on file systems that keep times in units smaller than microseconds, and we didn't catch it.

The bug was that some places in the code rounded to the nearest millisecond, and some truncated, which results in inconsistencies.  The fix was to always truncate.  Timestamps for files previous uploaded with rounded times will not match those with truncated times in the latest release.

A workaround is to sync with `--skipNewer`.  Or, to fix the timestamps, sync once with `--replaceNewer` to update the times in B2, and then things will be fine.

**Comment by GlitterCakes** [comment]
Is `--replaceNewer` going to literally replace every file in B2 though if the dates have been wrong due to a bug? I have almost 20tb of data in B2 I can not simply rerun this whole backup.

**Comment by bwbeach** [comment]
Yes.  That's what `--replaceNewer` will do.  

I would recommend `--skipNewer` until we get this straightened out.

I think it would be a good idea, for the next release, to teach the code to ignore time differences of 0 to 1 second.

**Comment by GlitterCakes** [comment]
Using `--skipNewer` is going to ignore locally modified files and not sync them though correct? So if I change files on my end they will not overwrite those in B2?

**Comment by bwbeach** [comment]
No.  It's the other way around.  `--skipNewer` says that if the copy in B2 is newer that the local file, it just won't do anything.  

This is what the doc says:

```
    Files at the source that have a newer modification time are always
    copied to the destination.  If the destination file is newer, the
    default is to report an error and stop.  But with --skipNewer set,
    those files will just be skipped.  With --replaceNewer set, the
    old file from the source will replace the newer one in the destination.
```

**Comment by GlitterCakes** [comment]
I'm gonna take a step back here and say that a bug like this is completely absurd for a product you're selling with the idea of business level service. Was this even tested? Doesn't look like it. Between this problem and the random connection errors, and having so much data on the line (20tb) I now know that I can not trust this software at all to safeguard my companies data. The developers can't even follow the API set forth by their own company successfully.

I switched to rclone and it works flawlessly.
