### ISSUE TITLE
Arrow dependency restrictions prohibiting updates of B2

### ISSUE THREAD

**Issue by taz77** [Backblaze/B2_Command_Line_Tool#551]
The arrow package is now at version 0.13.0. B2 has a restriction of no greater than 0.12.1. This is preventing B2 from upgrading with an update of all outdated pip packages. Can we dependency updated in B2?

Reference: https://github.com/crsmithdev/arrow/releases

**Comment by ppolewicz** [comment]
It seems that you know what you are talking about. Perhaps you could just create a Pull Request with the mentioned change?

**Comment by taz77** [comment]
I have never written a single line of Python, so it would take me a long time to do so.

**Comment by ppolewicz** [comment]
Ah, I see.

**Comment by sww1235** [comment]
It seems that the only thing holding back updating the arrow version is dropping support for python 2.6. Is there any reason to keep hanging on to support for such an old version of python? 

I think it makes sense to drop support for 2.6 in order to improve user experience when trying to install the CLI tools using pip.

With python 2 going EOL in less than a year, the change won't matter for long.

I can create the pull request if dropping 2.6 support is something that is desired.

**Comment by taz77** [comment]
Wow..  2.6 was end-of-life 5 years and 4 months ago! I think 2.6 support can and should be ended. I always use the rule that once security updates have stopped being released, you drop those versions of a language.
