### ISSUE TITLE
Deleting and recreating a bucket with the same name causes error

### ISSUE THREAD

**Issue by k2l8m11n2** [Backblaze/B2_Command_Line_Tool#567]
1. Create a bucket with name `foo`
2. Use the command line tool to perform some operation on it so it gets added to `buckets` in `~/.b2_account_info`
3. Delete the bucket
4. Create it again with the same name (`foo`)
5. Try to use it with the tool
6. `ERROR: Unknown error: 400 bad_bucket_id Bucket <hash> does not exist`

**Comment by pawelwilczynski** [comment]
Here's my suggested solution
https://github.com/Backblaze/B2_Command_Line_Tool/pull/592/files

**Comment by jlarmstrongiv** [comment]
Any updates on this issue?  I ran into it today.  Is there any solution other than deleting `~/.b2_account_info` and logging back in?

**Comment by ppolewicz** [comment]
Hi John,

Let me address your workflow first and next I'll provide a workaround in case you'd like to keep it as it is against my advice. Your choice ;)

Let me first explain a couple of things:
1. Backblaze B2 has _globally unique_ bucket names. This means that if _I_ create a bucket using some name, then _you_ cannot create a bucket with the exact same name.
2. B2 allows a bucket to be created under a name at which a bucket existed in the past, once the old one using the name is deleted and once the deletion is "processed". I don't know how it works exactly - sometimes it is almost instant, sometimes you delete a bucket, get a confirmation of its deletion, then you try to create it again and you get an error. Sometimes the bucket can be fully removed in less than a second. Sometimes it can take some time. I have seen it take a few minutes a few years ago when I did some heavy testing. Due to the globally unique bucket name and a race condition, it is possible that you will delete a bucket and after it is reclaimed but before you create it again, someone else creates it first. In such case the bucket name can stay unavailable to you forever. Bucket name reclamation is not documented anywhere - to my knowledge Backblaze provides no guarantees on if and when the reclamation happens, so your software, if you care about its stability, should not rely on reclamation (or any other undocumented behavior of any cloud, for that matter).
3. The only thing you cannot change on a bucket after it is created, which would require the bucket to be recreated is `fileLockEnabled`. I doubt your workflow requires changing buckets from not `fileLockEnabled=False` to `fileLockEnabled=True` AND you need to use the exact same bucket name,, but if this is really that particular case, please go ahead and use a workaround documented below. (ok technically if you have created your bucket a very long time ago it can have no `s3` in options, so recreating a bucket might be necessary in order to enable s3 on it)

Because of:
1. Buckets being globally unique (someone can "steal" your bucket name, on purpose or by accident)
2. The potential delay/asynchronous nature with bucket name reclamation
3. Lack of really a good reason to recreate buckets in the first place

I'd recommend that you consider changing your workflow to not recreate buckets using the same name.


# The workaround

The easiest workaround is to run `b2 list-buckets` after `b2 delete-bucket` or after `b2 create-bucket`, but before you start using the new bucket.


# Why won't we just fix it

There are quite a few reasons:
1. One user complains about this issue every 5 years or so
2. The workflow for this case is usually flawed and a valid use case is extremely rare (arguably - if your application is using a hardcoded bucket name and you keep recreating it and someone evil finds out about it, it's vulnerable to an attack)
3. A very easy workaround exists
4. Code changes required to fix this would be substantial and would decrease readability of the code. Reviewing and testing the fix would require effort which would be much better spent elsewhere even if someone contributed the implementation. Furthermore, the way b2sdk is currently architected would make the fix error prone.

In other words, I think it's really a but not worth fixing.

**Comment by jlarmstrongiv** [comment]
Thanks for your detailed explanation @ppolewicz !  

My workflow uses cloudformation to create and destroy all resources associated with my app.  I am hacking on backblaze to the stack, which is why I ran into this bug.

You made very valid points—I’ll be sure to keep this in mind as I’m developing.  I’ll see if there's another workaround I can use.  

I have a few buckets I should recreate with the `s3` options, I’ve started using that awesome feature with my latest projects.
