### ISSUE TITLE
Monitor download consumption of application key

### ISSUE THREAD

**Issue by mittster** [Backblaze/B2_Command_Line_Tool#575]
I've taken a detailed look at your API and none of the functions seem to be relevant to getting information about download consumption.

Lets take a look at practical example...  Each app key is given to a user.  User performs all of its upload and download using this key. He is also restricted to path `/bucket1/user1/`. Since I am paying for the download bandwidth, I'd like to monitor download consumption. 

Which API should be called to get this information?

**Comment by ppolewicz** [comment]
Hey @mittster, this looks like a question not really about the b2 command line tool, but about the b2 service itself. For that, you should contact b2 support.

**Comment by mittster** [comment]
Hello @ppolewicz! 
I already did and Mr. Bob from the support team said I should post it on github, because it relates to CLI.

Anyway.. it's a simple question. Does CLI supports monitoring bandwidth on application key level? Or should I say, does it support download bandwidth monitoring at all? Pretty much any information about it download consumption intrigues me.

**Comment by ppolewicz** [comment]
I'm puzzled. How does it relate to CLI?

SDK and CLI could be extended to track download usage, but the user could take the application key and use it with some other application, which does not track usage. As far as I know, there is no way to pull the information about used bandwidth, per key, from the server (or if there is a way, it is not documented in the official API). Therefore CLI cannot deliver this reliably, unless you actually control all the application keys and users never see them. Is that the case?

**Comment by mittster** [comment]
>  but the user could take the application key and use it with some other application, which does not track usage.

This is precisely why I'd like to interrogate your servers (I am using CLI for that) for download consumption. There is no point in giving app keys directly to users if you can't monitor bandwidth. All it takes is a few malicious user that spend 1000TB and you are out of business. Moreover, I can't even stop the user because I don't know which one. 

Anyway, thanks for a swift reply. I'd like to submit feature request. To whom should I submit it?

**Comment by ppolewicz** [comment]
As you say, this is not a CLI-centric issue - it's server-side and the CLI is a few layers away from it.

In order to do what you need, I think we need the following things to happen:
1. Submit a feature request to B2 support so that the B2 server team introduces a new functionality
1. When that's done, submit a feature request to `b2-sdk-python` so that it adds support for the new feature
1. Finally, submit a feature request for the CLI to provide the functionality from command line

Currently the team that manages `b2-sdk-python` and CLI is almost exactly the same, so we may get away with a common ticket for points 2 and 3... However I think what you really need is not just the ability to monitor the download consumption, but actually **per-key limits** and **full per-key billing** (tracking transactions, downloads - and maybe (currently free) uploads too). Per-key limits would allow you to avoid the excessive usage of the bandwidth in the first place, as opposed to going out of business **when at least you know which user has ruined you** 😄

The question is whether implementing this server-side makes sense for B2 service. Will the business improve significantly if this low-cost storage gets per-key limits and usage tracking?

Alternatively, you might want to consider different architectures, such as:
- implement a proxy server using an extended version of b2-sdk-python and its own security, so you'd do accounting on your end, but put it on a [server close to b2 with free transfer](https://www.backblaze.com/blog/introducing-cloud-compute-services/)
- [integrate with cloudflare](https://www.backblaze.com/blog/backblaze-and-cloudflare-partner-to-provide-free-data-transfer/) which has a free "unlimited" plan. Not sure if that's good for your users though, CF may not be the best choice if the data is not public.

**Comment by mittster** [comment]
Thank you for a very detailed answer. I have indeed originally asked the support for app key limits. After learning that this feature is not implemented I lowered my standards and asked about bandwidth monitoring 😄 My next step was to ask about monitoring the number of times the file is downloaded, but looking at the API function names it is clear that this isn't implemented.

Again, thank you for outstanding support!
