### ISSUE TITLE
fileId -vs- bucket and filename

### ISSUE THREAD

**Issue by molomby** [Backblaze/B2_Command_Line_Tool#620]
I'm a new user of the service and the `b2` CLI. It's completely unintuitive to me why some commands take `fileIds`, eg..

```sh
b2 make-url <fileId>
```

Other commands (seemingly related in this case?) take a `bucket` and a `filename`, eg..

```sh
b2 get-download-url-with-auth [--duration <durationInSeconds>] <bucketName> <fileName>
```

While still others come in a pair, so either can be used:

```sh
b2 download-file-by-id [--noProgress] <fileId> <localFileName>
b2 download-file-by-name [--noProgress] <bucketName> <fileName> <localFileName>
```

Meanwhile, converting between these values seems unnecessarily complicated.

Going from a `fileId` to `bucket` + `filename` can be done but (unless I'm mistaken?) requires parsing JSON and text from multiple calls:

```sh
INFO=$(b2 get-file-info $FILE_ID)
FILE_NAME=$(echo $INFO | jq -r .fileName)
BUCKET_ID=$(echo $INFO | jq -r .bucketId)
BUCKET_NAME=$(b2 list-buckets | egrep $BUCKET_ID | sed 's/  / /g' | cut -f3 -d' ')
```

Going from `bucket` + `filename` to `fileId` is easier but still seems harder than it should be. The best solution I can find is:

```sh
FILE_ID=$(b2 list-file-names $BUCKET_NAME $FILE_NAME 1 | jq -r '.files[0].fileId')
```

I mean, if you're going to make different commands use different but equivalent identifiers, at least make it easy to convert between them, right?

I'm sure there are technical and historical reasons for all this but I'm not sure users of the CLI should need to care. Personally, I'll be interacting with the service solely via CLI and having all this complexity leak though seems very much to be making my life harder for no gain.

**Comment by ppolewicz** [comment]
The reasons are technical, not historical.

In one b2 bucket you can store more than one object under the same name. If you would like to delete an object with a given name, the server may have more than one. That is why it is necessary to provide the fileId in many cases - file name may point to multiple objects. Does it make more sense now?

To take your example, going from `bucket` + `filename` to `fileId` may not be that easy because you can get more than one file.

**Comment by molomby** [comment]
Ah, right. Yep, I missed that somehow. Thanks
