### ISSUE TITLE
ls with folder name return empty result

### ISSUE THREAD

**Issue by magarwal-reef** [Backblaze/B2_Command_Line_Tool#623]
![Screenshot from 2020-05-19 20-01-47](https://user-images.githubusercontent.com/54530473/82432252-643d9a80-9aad-11ea-9993-eff0616aeb8d.png)

**Comment by magarwal-reef** [comment]
I am working on it

**Comment by ppolewicz** [comment]
please add `--json` output format to `ls` and remove `list-file-names` and `list-file-versions` legacy commands while you are at it. Those are no longer supported by b2sdk, from now on there will be one command to list files (instead of three) and it will accept various parameters for output format customization (sort of like `ls` on linux)

**Comment by ppolewicz** [comment]
I am adding it in #632

**Comment by ppolewicz** [comment]
ok so this is actually correct behavior. In `ls` you pass in a name of the "folder" and in `list-file-names` you could pass a `startName`. The meaning is different.

We think the user doesn't care about such low-level stuff, that's why b2sdk removed it from the interface. The user wants either a list of all files, or a list of top-level files (skipping the contents of the "folders", except for one entry per folder that is getting returned).
