### ISSUE TITLE
Support "Restore from B2" snapshot functionality from command line

### ISSUE THREAD

**Issue by brandongalbraith** [Backblaze/B2_Command_Line_Tool#624]
Checking if a PR would be welcome that supports orchestrating a snapshot operation (ie HTTPS POST to https://tree*.backblaze.com/user_restore.htm with necessary form data) from Backblaze Computer backups to B2.

Currently, I must use the web UI to perform such a snapshot, and would rather use the `b2` command line utility for scripting/automating/scheduling such jobs.

**Comment by ppolewicz** [comment]
Hey, thanks for checking with us. Let me discuss it internally and get back to you in a couple of days.

**Comment by ppolewicz** [comment]
BTW there is another feature in development right now that will let you restore from a point in history (not a snapshot), where you'd call sync with a parameter that sets a date from which you want to restore. This way if you have deleted some data and a sync was ran later, you can easily get the files which were deleted.

**Comment by brandongalbraith** [comment]
@ppolewicz That's great to hear! I would be happy to be a beta tester for any features that are "less than general availability" quality.

**Comment by ppolewicz** [comment]
@brandongalbraith I am very curious what your operation looks like. Can you please describe your workflow? We are more likely to implement features that may support you if we know what you are doing :)

**Comment by brandongalbraith** [comment]
@ppolewicz Great question! My use cases usually revolve around taking a point in time snapshot of a folder structure on my Mac as a zip file, whether that's a git project, the iMessages directory (to save iMessages for sentimental purposes, such as when I lost a loved one and wanted to preserve their messages off my local file system), or the Mac Photo Library (as it is my canonical original photo storage for every photo I've ever taken, and therefore I need to protect not only against image loss but also image or metadata corruption).

Usually, I'd just compress the directory into a zip file and then upload to B2, and this works great for smaller directories! Unfortunately, for data sets that are large (my iMessages backup was 5GB, my Photo Library ~200GB), the bottleneck is my residential internet connection. As the Backblaze Mac client has already uploaded all of my files, and your storage system already has my filesystem state, it seemed ideal for these use cases to have a command that I could use to offload these snapshot operations to on the Backblaze infra side (similar to `b2 copy-file-by-id` to copy files bucket to bucket).

I'd imagine the command might look something like my below example, with `<localDirectoryName>` being self explanatory and `<namePrefix>` indicating the name of the resulting `.zip` file containing the directory contents that ends up in the B2 bucket for my account when restores from the computer backup are made to my account's B2 bucket for that purpose.

```
b2 snapshot <localDirectoryName> <namePrefix>
```

If this is out of scope for the B2 command line tool, not a problem at all. I can make due with my own command line tools, and should be able to scrape the Backblaze web UI with my credentials to get the params I need to emulate the functionality I'm targeting.

**Comment by ppolewicz** [comment]
How many files are getting zipped up like this?

What is the minimum and maximum size of the file? Specifically, are files in your patterns smaller than 5MB or larger than 5GB?

Is compression imporatant? It kind of feels like compression is not important as you are dealing with small text files (so compression won't matter much) or image/video which do not really compress all that much.

**Comment by brandongalbraith** [comment]
30k-200k files. Many are small (1MB-5MB), but there are outliers anywhere from 30-50MB (videos from Photo Library) up to ~1GB (Photo Library Sqlite database). Compression is not important, and could be set to `-0 store only` on whatever process your infra kicks off for bundling to conserve compute resources, as zip is simply used as a container for the data.

**Comment by ppolewicz** [comment]
If many files are small then synthesizing the thing using large file upload/copy would still be possible (it would use files larger than 10MB), but problematic (small files would need to be reuploaded, also 5MB would have to be reuploaded for every file due to local header of zip file. We could try to use tricks to put large files next to small files to save half the upload, but it is still way worse than a cloud-side snapshot.

**Comment by brandongalbraith** [comment]
> but it is still way worse than a cloud-side snapshot.

Definitely! Hence the desire for the B2 command line tool to kick off a cloud-side snapshot task that bundles the directory specified instead of re-uploading data that is already being stored in your storage system. The intent is to avoid any further data upload operations, as Backblaze already has the data in question.

**Comment by ppolewicz** [comment]
This would require either the API to be extended (and the demand for this feature does not seem to be all that great - snapshots are supported for quite a long time and nobody mentioned them until a week ago) OR it would require instrumentation of the web admin panel, which:
- would be brittle (every time they update their UI, instrumentation could break)
- would cause problems with 2FA
- would require storage of the master password

Furthermore the overlap between b2cli and the web admin panel instrumentation tool is slim. Even if we would build it for some reason, we would not keep it in the same repository.

I think one day b2 server will expose an endpoint for creating snapshots, then b2sdk will start supporting it and finally b2cli will expose that functionality, but for now, due to reliability and security concerns, I think that's a no go.

If you will create a tool that is capable of triggering the snapshots and you will use b2sdk, please stay in touch, getting feedback from b2sdk users is hard and being able to prioritize features and improvements with real users such as yourself is valuable for me.

**Comment by brandongalbraith** [comment]
Sounds good, thanks for the consideration!

**Comment by brandongalbraith** [comment]
I was able to accomplish this with tooling outside of the Backblaze ecosystem, closing.
