### ISSUE TITLE
Please add an option to authorize_account to let me specify a base url.

### ISSUE THREAD

**Issue by certainmagic** [Backblaze/B2_Command_Line_Tool#642]
The goal is to let us run the CLI against other B2 instances without having to change the code to add additional arguments like the "--staging" and "--dev" arguments that currently exist.

Here's a potential example:

   b2 authorize-account --baseUrl https://api.backblazeb2.xyz

thanks,
ab

**Comment by ppolewicz** [comment]
Hey,

I see an elaborate security threat with this, where someone capable of injecting a parameter to CLI invoication when parameters are not properly quoted, might be able to trick the CLI into uploading a file into something that is not really a b2 server.

I think B2 developers should use a slightly modified version of b2cli. We know that in java sdk there are special headers that one might add to cause the server to behave in a certain way. Those can be exposed to CLI as well (code snippet was sent to Keith a few weeks back), for example via environment variables.

I think this custom version of b2cli should also support setting the baseurl via environment variable. In fact, if this is done, then we could remove `--test` and `--dev` from the CLI (again, if someone can inject `--dev` into command-line, they could escape https. This is sort of the fault of whoever is writing the server in a way that doesn't properly quote parameters, but if we can avoid such possibility completely, maybe we should?).

Does this seem feasible? If it does, we'd prepare the CI to produce two binary versions - b2/b2.exe for regular users and b2dev/b2dev.exe for internal usage in B2 team, with additional capabilities (setting environments and headers via environment variables).

**Comment by certainmagic** [comment]
Hi Paweł --

I think we share a lot of goals, including keeping the sdk and cli clean and simple and avoiding adding possible security issues.  I always appreciate how you think about what people are asking for and why they are asking for it instead of just doing what they're asking for.  I also appreciate your always looking for ways things could go wrong.  :)

One of the nice things about the existing cli is that we can all just use it the same way customers do.  Are you imagining that binary would be in the same package?

Separately, I'm curious, if I can inject "--dev" into a command line run by a server, how much harder it is to inject something like "$(curl ...post the account info file or some env vars...)".  I'm guessing this is a little harder attack because some basic validation might block '$' or parenthesis?

Two other things:
- We can change the url for "--dev" to "https://api.backblazeb2.xyz".
- My short term goal is to be able to use the base url "https://api.backblaze.pet".  I'd be ok just adding it with "--pet", but I figured it'd be good to stop having the custom hard-coded lists.

thanks,
ab

**Comment by ppolewicz** [comment]
Thanks - I've literally had thousands of bugs come through my hands. I guess it shaped the way I approach things.

I wouldn't put it in the same package, but I would make it very easy to install for B2 staff members (`wget https://backblazeb2.xyz/linux/b2dev && chmod +x b2dev`? actually you won't even need python and a working pip to do this)

`--dev` being on http - yeah, it's a problem. That's why I'd rather remove it from "public" b2cli - for non-B2 staff members it only serves as a potential security vulnerability, there is no other benefit of having it there. If we were unable to split things into b2 and b2dev, we'd have to keep it open, but now that we can split it, we might just go ahead and do it.

As for the creative "security" filters some developers use, they may be vulnerable in various ways. Some would be more effective and some would be less effective. Filtering out all characters that are not numbers, underscores, dashes and (accidentally!) spaces as form field validation could happen.

I think for `--dev` you should keep http because redirecting something to a local server + network packet inspection is a powerful tool for debugging. Lets not throw it away.

Is the new installation method acceptable? The only difference between `b2` and `b2dev` will be that it will allow setting an environment variable that points to the environment during authorize-account (and in the future maybe you will be able to inject headers, but I was told those kind of tests are written in python and will use a context manager that I've sent to Keith).

**Comment by certainmagic** [comment]
Let me talk to some co-workers about this.  I'll get back to you.

**Comment by bwbeach** [comment]
I agree with @certainmagic that if somebody can inject something into my command-line, they have enough power to do what they want.  My inclination would be to keep things simple, and avoid having a separate package.

One advantage to using the same package is that we use extensively inside Backblaze, so it gets high-volume usage.  If something went wrong with it, we would know about it.

**Comment by ppolewicz** [comment]
All right. What about the name, can it be `--environment`? Should it be visible in `--help` or can it be a hidden option?

**Comment by bwbeach** [comment]
Hidden is fine.  It will only be used inside Backblaze.

And `--environment` is OK.  Looking at the docs, the name `baseUrl` is used for what `b2_authorize_account` returns to use for subsequent calls.

**Comment by ppolewicz** [comment]
All right, everything seems clear. I think on b2sdk side we could change the "realm" parameter of `b2dsk.v1.B2Api.authorize_account`, which up until now was a string "production" (or "test" or "dev"), to still use the [REALM_URLS mapping](https://github.com/Backblaze/b2-sdk-python/blob/b103939cc19020a5f7cae7a6e26f1073b5ba2232/b2sdk/account_info/abstract.py#L32) 

[here](https://github.com/Backblaze/b2-sdk-python/blob/1b5ebdc96587853f19965a0874036de1e932812d/b2sdk/session.py#L111), but changed from:
```python
        realm_url = self.account_info.REALM_URLS[realm]
```
to
```python
        realm_url = self.account_info.REALM_URLS.get(realm, realm)
```
small changes to option parsing on b2cli would also be needed. @bwbeach is this design acceptable, or should we do a full-blown parameter addition and support both old and one separately?

**Comment by bwbeach** [comment]
This is fine.

**Comment by certainmagic** [comment]
Thanks, Paweł. :)
