### ISSUE TITLE
b2 ls --recursive throws Too Many Requests error

### ISSUE THREAD

**Issue by TechKat** [Backblaze/B2_Command_Line_Tool#659]
To put in some context: I have recently moved the storage of a website I run to BackBlaze B2. There's millions of files and each file is recorded on a database for reference. It came to my attention that the reported total filesize accounted for in the database doesn't match with what BackBlaze's control panel reports.

For example: My database says there should be a total of 1,234 GB stored. BackBlaze control panel says there's 1,456GB in the bucket.

So, I wanted to generate a filelist of every file stored in my bucket so I could compare the filelist with what the database has, by using the following command:
`b2 ls --recursive <bucketName>`

It runs well for a short time then throws a Python error that Too Many Requests were made:
```
ConsoleTool command error
Traceback (most recent call last):
  File "b2/console_tool.py", line 1500, in run_command
  File "b2/console_tool.py", line 1081, in run
  File "site-packages/b2sdk/bucket.py", line 277, in ls
  File "site-packages/b2sdk/session.py", line 213, in list_file_names
  File "site-packages/b2sdk/session.py", line 364, in _wrap_default_token
  File "site-packages/b2sdk/session.py", line 370, in _wrap_token
  File "site-packages/b2sdk/session.py", line 385, in _reauthorization_loop
  File "site-packages/b2sdk/session.py", line 375, in _api_token_callback
  File "site-packages/b2sdk/raw_api.py", line 456, in list_file_names
  File "site-packages/b2sdk/raw_api.py", line 302, in _post_json
  File "site-packages/b2sdk/b2http.py", line 345, in post_json_return_json
  File "site-packages/b2sdk/b2http.py", line 311, in post_content_return_json
  File "site-packages/b2sdk/b2http.py", line 139, in _translate_and_retry
  File "site-packages/b2sdk/b2http.py", line 59, in _translate_errors
b2sdk.exception.TooManyRequests: Too many requests
ERROR: Too many requests
```

I understand BackBlaze has a ratelimit in place to prevent an overload of their systems. I've contacted their support for advise, or perhaps some assistance in acquiring the command's full output to file so I could run some comparisons on my server, however they were unable to do so, and directed me to the Github issues page.

This was partially their response:
```
For something like this, I would also suggest posting to our B2 command line github to see if you can find some further insight or even request that this behavior be changed. https://github.com/Backblaze/B2_Command_Line_Tool
```

Has anyone had a similar issue and found a workaround/solution?

I'm still getting used to using the CLI tool, and since it's a live bucket in use to retrieve data from, I want to be extra careful I don't accidentally wipe it clean.

**Comment by ppolewicz** [comment]
You've come to the right place!

b2sdk/b2cli handles 429 rate limit already: https://github.com/Backblaze/b2-sdk-python/blob/778d5f43f22f5407821f55fb3e18fd76c8db7070/b2sdk/b2http.py#L124
it seems that here it didn't work, I think the scenario was that everything was running smoothly, until a few of your requests have terminated with an error (due to network trouble for example, it's pretty common) and the _last_ attempt before reaching the limit has hit the 429 server-side rate limit.

@bwbeach I think [this loop](https://github.com/Backblaze/b2-sdk-python/blob/778d5f43f22f5407821f55fb3e18fd76c8db7070/b2sdk/b2http.py#L117) should be restructured to not increase try_count due to 429-type responses, or there should be different counters for 429-type "failures" and the "real failures". We need to restructure the entire retry mechanism one day, but we are not ready for that just now so a smaller fix is appropriate here. What do you think?

**Comment by ppolewicz** [comment]
Also, it might be a web admin display/understanding issue, see [this](https://github.com/Backblaze/b2-sdk-python/issues/158)

**Comment by TechKat** [comment]
@ppolewicz Understandable that it might be a formatting issue on BackBlaze's control panel and there's no problem at all. But it'd give me piece of mind knowing everything is accounted for.
