### ISSUE TITLE
How to use b2 without authorize-account

### ISSUE THREAD

**Issue by lohman** [Backblaze/B2_Command_Line_Tool#664]
Hi there,

I'm trying to figure out how to use the environment variables with the b2 cli, and haven't figured out how to make it work yet.  I opened a support case and they had no idea and sent me here.  So hoping you can help.

The request would be, if it's possible, to update formal documentation with examples to demonstrate how to use the b2 cli without running authorize-account.  If this is possible, also asking for the b2 error to add environment variables as an option.  For example, the error currently says this:

"ERROR: Missing account data: 'NoneType' object is not subscriptable  Use: b2 authorize-account"

Would be helpful to expand it to something "...Use: b2 authorize-account or export the B2_APPLICATION_KEY_ID and B2_APPLICATION_KEY environments variables and do other stuff"

Until the docs exist, maybe you could help me understand how to get this working.

I do
export B2_APPLICATION_KEY_ID=stuffhere
export B2_APPLICATION_KEY=stuffhere

and still, it says "ERROR: Missing account data: 'NoneType' object is not subscriptable  Use: b2 authorize-account"  what else needs to be on the command line to make b2 work without the ~/.b2_account_info file?

**Comment by ppolewicz** [comment]
Hey,

b2cli needs a file to store bucket_id-bucket_name mapping, upload tokens and other stuff. While technically we could try to make it so it gets the credentials from the env, you still need to park this maps somewhere.

Why are you trying to avoid `~/.b2_account_info`?

**Comment by lohman** [comment]
Ok, thanks.  Would prefer to not have to copy that file in.  I'm looking at
automating backups by standing up a clean container, running as little
shell script as possible, then tearing down the container.  It would be
nice if I could just pass all of that as variables so that I don't have to
do file handling.  It's not a huge problem but it would be nice.  Ideally
I'd prefer to just feed all of it as a parameter on the command line.  In
this scenario I'm not concerned with the security implications because I'm
handling the security with containers instead of file permissions.

Maybe you'd consider it as a future feature to let me pass everything in
that file as a command-line parameter or environment variable.  But for now
I have my answer, thank you.

Regards,

--Christopher

**Comment by ppolewicz** [comment]
You can pass credentials with `B2_APPLICATION_KEY_ID` and `B2_APPLICATION_KEY` so that you don't need to feed it awkwardly via stdin
, so your command will need to authorize and then do the backup (I assume sync?), but assuming you are wiping `~/.b2_account_info` (which btw you shouldn't do yourself, but via `b2 clear-account`), then bucket-name-to-id cache and the list of upload tokens will need to be refreshed which will add a few seconds to your backup cycle and consume a few transactions (though the limits are pretty high and the cost of those transactions on a paid account is very small).

While I still have you on the line, I'd like to ask for feedback for a future change in b2cli which would let you have more control over the retry mechanism - currently if any file fails to upload 5 times, we abort the entire sync and it seems that a better idea would be to assume that the backup window length is, lets say, 8 hours - and even if many retries happen over that time, that's still ok because you don't want your script to exit with a failure just because network was down for a few minutes. Is that how you see it too, or maybe you have another idea on how to deal with the retry limit?

**Comment by lohman** [comment]
With regards to your retry mechanism.  Rsync is a model that I prefer for such things.  My preference would be that it tries once and fails by default.  Then it gives me command line switches to control retries by number, or time.  Either repeat and retry 10 times per file  (run the entire sync once.  retry each file 10 times)  Or retry the entire sync job for hours.

**Comment by lohman** [comment]
I prefer the default behavior to fail fast so that I can easily work through things and get it working, before I let the big sync run and walk away.  I also like to have switches to help with latency, to define the timeout time itself for slow links.  My sync job might be on fail/retry because it cannot tolerate 200ms of latency.  I deal with this often with NPM pulling down modules.  I have to use the -timeout=9999999 switch often to compensate for bad latency or packet loss.  Having the --timeout option on the cli (if it doesn't exist) would also be a nice option to have along with the --retry switches.

**Comment by mlech-reef** [comment]
#665 has been implemented in [b2 2.2.0](https://github.com/Backblaze/B2_Command_Line_Tool/releases/tag/v2.2.0). I'm closing this ticket.
