### ISSUE TITLE
b2 command line tool depends on b2sdk v1.2.0

### ISSUE THREAD

**Issue by tblancher** [Backblaze/B2_Command_Line_Tool#682]
The b2 command line tool depends on b2sdk v1.2.0, but the latest version of b2sdk-python is v1.3.0:

https://github.com/Backblaze/b2-sdk-python/tags

The maintainer of the backblaze-b2 and python-b2sdk packages in the Arch User Repository (AUR) cannot update python-b2sdk in the AUR because the CLI tool still depends on the old version, and is broken when the new python-b2sdk is installed.

**Comment by mlech-reef** [comment]
Hi!

Shouldn't this be sorted out by the dependency resolver of the package manager? I don't think this is an issue of the CLI as we can release a non-backward compatible version of the SDK without releasing CLI at the same time. However, the requirements have been adjusted to better work with SemVer 2.0 recently on the master branch (see below), but the new version of CLI is not yet released.

![image](https://user-images.githubusercontent.com/63924630/108081388-33f14f80-7071-11eb-8948-b71a4e3c76ac.png)

**Comment by tblancher** [comment]
I only posted here at the suggestion of the AUR package maintainer.  I'll let them know you've updated the requirements.txt to reflect that the CLI tool needs `b2sdk<1.3.0`.

Thanks.

**Comment by ppolewicz** [comment]
@mlech-reef b2cli [v2.1.0](https://github.com/Backblaze/B2_Command_Line_Tool/releases/tag/v2.1.0) [requires](https://github.com/Backblaze/B2_Command_Line_Tool/blob/7c3adb42ca5fa8496f961e1ad40229c043c3f743/requirements.txt) `b2sdk>=1.2.0,<1.3.0`
but b2sdk [v1.3.0](https://github.com/Backblaze/b2-sdk-python/releases/tag/v1.3.0) is already released

We could release b2cli v2.1.1 to fix it the requirement, but v1.3.0 [changelog](https://github.com/Backblaze/b2-sdk-python/releases/tag/v1.3.0) doesn't show a huge impact on the cli.

AUR maintainer can wait for us to release a new version of CLI (which we are not in a great hurry to do right now because there are barely any changes since last release) or they can include both b2sdk [v1.2.0](https://github.com/Backblaze/b2-sdk-python/releases/tag/v1.2.0) and b2sdk [v1.3.0](https://github.com/Backblaze/b2-sdk-python/releases/tag/v1.3.0).

**Comment by ppolewicz** [comment]
A-ha! @mlech-reef found a way to adjust the schedule so that a release of some new functionality could happen soon, fixing this problem as a side effect.

**Comment by mlech-reef** [comment]
There should be no problem like that with recently released b2 v2.2.0 and b2sdk v1.4.0, however, it may still occur in future releases, but less frequently.

I'm closing this issue
