### ISSUE TITLE
Cannot create a file that already exists, but it doesn't

### ISSUE THREAD

**Issue by patdeuster** [Backblaze/B2_Command_Line_Tool#730]
I'm trying to run the b2.exe command line utility. 

When trying to sync a folder, I'm constantly getting this error:
![github upload](https://user-images.githubusercontent.com/87020348/124603094-90de7e00-de37-11eb-8c1e-b86177f9cb35.png)

The file doesn't exist though, at least not in the bucket I am pulling from.

I did try and set a file exclusion, but to no avail.

Support was less than helpful in getting this issue resolve. 

Does anyone have an idea on what is causing this?

Thanks

**Comment by ppolewicz** [comment]
It looks like there used to be a directory with some name which was then replaced by a file, or maybe the other way around, and a download failed in progress. Or maybe it's a symlink.

I suggest you try deleting `D:\Cloud Download\3_Unscripted\Psychic Kids\Sneak Peak_Master\.b2.sync.tmp` and see if it helps.

**Comment by patdeuster** [comment]
@ppolewicz ,

Thanks for getting back to me.

I should have mentioned this, the target folder is blank.

**Comment by ppolewicz** [comment]
🤔 Do you have an empty folder on B2 side or on local side?

**Comment by patdeuster** [comment]
@ppolewicz, this is on the local side. B2 side has data.

**Comment by ppolewicz** [comment]
Ok so the problem seems to be that you have an OBJECT in your bucket `ProMAX_Test_03/3_Unscripted/Psychic Kids/Sneak Peak_Master/` (please note the `/` being the last byte of the file name!). Sync doesn't support that. Generally you shouldn't do that, nothing good will ever come out of this ha ha.

Now sync should probably raise a more specific error, saying that syncing buckets with objects that have a trailing `/` in their name to a filesystem is not possible (though if you'd like to sync that between two buckets, that's ok I guess). I'm kind of wondering what created that weird file and why :)

I think you should inspect that object I mentioned and then you either delete it, or rename it via server-side copy+delete or something. I'm afraid (that if my diagnosis is correct), you can't just sync this bucket down without fixing it first.

It's a very hard issue, I wouldn't expect Backblaze first line of support to troubleshoot it, but it's good that you came here so that we could do what we just did :)
