### ISSUE TITLE
Connection error- certificate verify failed

### ISSUE THREAD

**Issue by st4302** [Backblaze/B2_Command_Line_Tool#771]
![b2](https://user-images.githubusercontent.com/68067693/145073960-dcb114ef-db87-4d81-adc9-86844c20d2f2.png)

Hello,

I tried to sync some files to my backblaze account last week but the syncing did not seem to work. Since then I have been getting a connection error which you can see on the image attached. How can I resolve this issue?

Thank you

**Comment by ppolewicz** [comment]
@st4302 I suggest that you use `b2-windows.exe` binary distribution from here: https://github.com/Backblaze/B2_Command_Line_Tool/releases

It looks like you might still be using an ancient version of b2 command line tool.

If this problem will persist on the modern environment, please use the `--verbose` switch to display diagnostic information when running b2 command line tool and share the header of what it will output with us to enable further investigation.

**Comment by ppolewicz** [comment]
this might be related to https://github.com/Backblaze/b2-sdk-python/issues/294

**Comment by st4302** [comment]
Thank you for your reply. Can I use `sudo pip install b2` to install a new version? I am using linux on a remote server.

**Comment by ppolewicz** [comment]
Oh I'm sorry it looked like a Windows console on the screenshot you've posted.

Unfortunately I suspect that the problem you are facing is caused by the part of your environment that is not managed by pip, so I recommend that you use the binary release. On linux you can run
```
wget https://github.com/Backblaze/B2_Command_Line_Tool/releases/download/v3.1.0/b2-linux
```
to get the program and
```
chmod +x b2-linux
```
to make it executable.
Then you can use it by running `./b2-linux` instead of `b2`. You don't need to uninstall the old version.

**Comment by st4302** [comment]
Thank you so much! It works!
