### ISSUE TITLE
Installing python b2, error 'No matching distribution found for docutils..'

### ISSUE THREAD

**Issue by MrM40** [Backblaze/B2_Command_Line_Tool#844]
I would like to run the python version of b2, not the embedded `b2-linux` binary.

When I try to install the pip package with
```
pip3 install b2
```
I get
```
Collecting b2
  Using cached b2-3.6.0.tar.gz (92 kB)
Collecting arrow<2.0.0,>=1.0.2
  Using cached arrow-1.2.3-py3-none-any.whl (66 kB)
Collecting b2sdk>=1.18.0
  Using cached b2sdk-1.18.0.tar.gz (313 kB)
ERROR: Could not find a version that satisfies the requirement docutils==0.19 (from b2) (from versions: 0.3, 0.3.5, 0.3.7, 0.3.9, 0.4, 0.5, 0.6, 0.7, 0.8, 0.8.1, 0.9, 0.9.1, 0.10, 0.11, 0.12, 0.13.1, 0.14rc1, 0.14rc2, 0.14, 0.15, 0.15.1.post1, 0.15.2, 0.16b0.dev0, 0.16rc1, 0.16, 0.17b1, 0.17, 0.17.1b1.dev0, 0.17.1, 0.18b1, 0.18, 0.18.1b0, 0.18.1)
ERROR: No matching distribution found for docutils==0.19 (from b2)
```

Tried to install docutils
```
pip3 install docutils
```
but get version 0.18.0

How can I fix this?
I'm running openSUSE 15.4 (kernel 5.14)

**Comment by ppolewicz** [comment]
It kind of looks like you are using a very old version of python which is not supported anymore. Could you please check `python --version`?

A quick google search confirms that the system of openSUSE 15.4 uses python 3.6 which is EOL already.

You can install 3.9 and use virtualenv... We are also going to provide a Docker image so that you can avoid all that if you can docker (though with 3.6-based system I imagine things like docker or docker-compose might not work either).
