### ISSUE TITLE
Can't upload FIFOs with upload-file

### ISSUE THREAD

**Issue by zkldi** [Backblaze/B2_Command_Line_Tool#911]
[The documentation states that you can use named pipes as upload sources](https://b2-command-line-tool.readthedocs.io/en/master/subcommands/upload_file.html), but it looks like [this commit](https://github.com/Backblaze/B2_Command_Line_Tool/commit/0bd4d9049380cfa5dbd009464defd279cd492fd9) in 2016 removed that functionality.

I'm looking to upload database backups from mongodb without buffering on disk, as we don't have a lot of storage space on the actual server.

I believe this functionality should work; can't really see why it was disabled?

**Comment by zkldi** [comment]
Looks like this might be a duplicate of #152, but the documentation being incorrect seems a little confusing. documentation issue might be a separate problem.

**Comment by ppolewicz** [comment]
Uploading from named pipes didn't work at the time - that's why it was disabled. Back then it was necessary to know the size of the file to upload it.

We have recently introduced the ability to stream files of any size via standard input (not named pipe, though maybe that could work soon too) and this has even been tested to work correctly, however during code review it turned out that adding 5 new configurable parameters to that feature is not really a good idea, so tweaking the parameters and their documentation was recommended. I'm not sure what happened next - I'll be talking to someone who worked on this tomorrow, so should find more information.

Would you be willing to test a pre-release version with the stdin upload feature? It'd be very nice to get some real usage out of this before we merge and release the first version as it's then easier to introduce backwards-incompatible changes to improve user experience.

**Comment by zkldi** [comment]
Sure, I'd love to test that pre-release as we could do with the feature and it's not the end of the world if our backups aren't going through for a week or so.

Let me know what I can do.

**Comment by zkldi** [comment]
Just tested this on my laptop and it all worked perfectly. STDIN input works and mkfifo works too.

**Comment by mjurbanski-reef** [comment]
Support for FIFO files and stdin has been implemented and released in `b2>=3.10.0`. closing. Happy uploads!
